import { getFinanceProvider } from "@/lib/finance/mock-provider";
import { FinanceProviderError } from "@/lib/finance/provider";
import { calculateValueMetrics } from "@/lib/finance/scoring";
import { buildVerdictExplanation } from "@/lib/finance/verdict-explanation";
import { buildDataStatus } from "@/lib/finance/data-status";
import { deriveSeries } from "@/lib/finance/series";
import { analysisProse, proseModelFromMetrics } from "@/lib/finance/prose";
import { resolveSecurity } from "@/lib/finance/exchanges";
import { makeTranslator } from "@/lib/i18n/translate";
import type { ValueMetricsResult } from "@/types/finance";
import type { ValueInvestingAnalysis } from "@/types/analysis";

export type AnalysisProgressCallback = (stage: string) => void;

// The stored prose is English; the display layer regenerates it in the
// viewer's language from the same generators (see lib/finance/prose.ts).
const enT = makeTranslator("en");

function confidenceFromScores(m: ValueMetricsResult): number {
  const notes = m.diagnostics.data_quality_notes.length;
  const base = notes === 0 ? 75 : notes === 1 ? 65 : notes === 2 ? 55 : 45;
  return Math.min(85, base + Math.round(m.composite_score * 0.1));
}

// ─── main export ─────────────────────────────────────────────────────────────

export async function analyzeTicker(
  ticker: string,
  onProgress?: AnalysisProgressCallback,
): Promise<ValueInvestingAnalysis> {
  onProgress?.("Fetching financial data...");
  const provider = getFinanceProvider();
  const dataset = await provider.getCompanySnapshot(ticker);

  onProgress?.("Calculating intrinsic value...");
  const m = calculateValueMetrics(dataset, undefined, dataset.sector);

  onProgress?.("Building analysis...");

  const security = resolveSecurity(m.ticker);
  const prose = analysisProse(proseModelFromMetrics(m), enT);

  return {
    ticker: m.ticker,
    exchange: security.exchange,
    sector: dataset.sector,
    company_name: m.company_name,
    currency: m.currency,
    current_price: m.current_price,
    analysis_date: new Date().toISOString(),
    valuation: {
      pe: m.valuation.pe,
      pb: m.valuation.pb,
      ps: m.valuation.ps,
      ev_ebitda: m.valuation.ev_ebitda,
      price_fcf: m.valuation.price_fcf,
      graham_number: m.valuation.graham_number,
      valuation_score: m.valuation.valuation_score,
      verdict: m.valuation.band,
      summary: prose.valuationSummary,
    },
    financial_health: {
      debt_equity: m.financial_health.debt_equity,
      current_ratio: m.financial_health.current_ratio,
      interest_coverage: m.financial_health.interest_coverage,
      fcf_consistency_score: m.financial_health.fcf_consistency_score,
      health_score: m.financial_health.health_score,
      verdict: m.financial_health.band,
      summary: prose.healthSummary,
    },
    business_quality: {
      roe_pct: dataset.latest.roe_pct,
      roic_pct: dataset.latest.roic_pct,
      gross_margin_pct: dataset.latest.gross_margin_pct,
      operating_margin_pct: dataset.latest.operating_margin_pct,
      revenue_stability_score: m.business_quality.revenue_stability_score,
      moat_score: m.business_quality.moat_score,
      quality_score: m.business_quality.quality_score,
      verdict: m.business_quality.band,
      summary: prose.qualitySummary,
    },
    intrinsic_value: {
      dcf_value_per_share: m.intrinsic_value.dcf_value_per_share,
      graham_value_per_share: m.intrinsic_value.graham_value_per_share,
      blended_intrinsic_value_per_share: m.intrinsic_value.blended_intrinsic_value_per_share,
      margin_of_safety_pct: m.intrinsic_value.margin_of_safety_pct,
      summary: prose.intrinsicSummary,
      // Per-model detail so the result prose can be regenerated by locale.
      nav_value_per_share: m.intrinsic_value.nav_value_per_share,
      ddm_value_per_share: m.intrinsic_value.ddm_value_per_share,
      pbroe_value_per_share: m.intrinsic_value.pbroe_value_per_share,
      normalized_roe_pct: m.intrinsic_value.normalized_roe_pct,
      intrinsic_method: m.intrinsic_value.intrinsic_method,
    },
    thesis: {
      bull_case: prose.bullCase,
      bear_case: prose.bearCase,
      red_flags: prose.redFlags,
      key_risk: prose.keyRisk,
    },
    diagnostics: {
      severe_balance_sheet_weakness: m.financial_health.severe_balance_sheet_weakness,
      weak_business_profile: m.business_quality.weak_business_profile,
      value_trap_risk: m.diagnostics.value_trap_risk,
    },
    final_verdict: {
      label: m.suggested_verdict,
      confidence_pct: confidenceFromScores(m),
      one_line_verdict: prose.oneLineVerdict,
      reasoning: prose.reasoning,
    },
    verdict_explanation: buildVerdictExplanation(m),
    data_status: buildDataStatus(dataset, m, security.exchange),
    series: deriveSeries(
      dataset.history_5y,
      dataset.provenance?.income_statement_period,
      new Date().toISOString(),
    ),
    sources: [
      {
        title: "Yahoo Finance (yahoo-finance2)",
        url: "https://finance.yahoo.com",
        used_for: "Financial statements, price data, and 5-year history",
      },
    ],
  };
}

export { FinanceProviderError };

export class ToolValidationError extends Error {
  readonly statusCode: number;
  constructor(message: string, statusCode = 400) {
    super(message);
    this.name = "ToolValidationError";
    this.statusCode = statusCode;
  }
}
