import type { ScreenableCompany } from "@/lib/screener/cac40";

// Full FTSE 250 constituent list sourced from Wikipedia (April 2025).
// Index membership is reviewed quarterly; acquired or delisted tickers will
// appear as error rows in the screener and can be ignored.
// All tickers use the Yahoo Finance ".L" suffix for the London Stock Exchange.
export const FTSE250_COMPANIES: ScreenableCompany[] = [
  { ticker: "3IN.L", sector: "Financials" },
  { ticker: "FOUR.L", sector: "Communication Services" },
  { ticker: "AAS.L", sector: "Financials" },
  { ticker: "ABDN.L", sector: "Financials" },
  { ticker: "ASL.L", sector: "Financials" },
  { ticker: "AEP.L", sector: "Consumer Staples" },
  { ticker: "ALFA.L", sector: "Information Technology" },
  { ticker: "ATT.L", sector: "Financials" },
  { ticker: "AO.L", sector: "Consumer Discretionary" },
  { ticker: "APN.L", sector: "Consumer Staples" },
  { ticker: "ASHM.L", sector: "Financials" },
  { ticker: "AIE.L", sector: "Financials" },
  { ticker: "AML.L", sector: "Consumer Discretionary" },
  { ticker: "ATYM.L", sector: "Industrials" },
  { ticker: "AGT.L", sector: "Financials" },
  { ticker: "AVON.L", sector: "Industrials" },
  { ticker: "BME.L", sector: "Consumer Discretionary" },
  { ticker: "BGFD.L", sector: "Financials" },
  { ticker: "USA.L", sector: "Financials" },
  { ticker: "BBY.L", sector: "Industrials" },
  { ticker: "BCG.L", sector: "Consumer Discretionary" },
  { ticker: "BNKR.L", sector: "Financials" },
  { ticker: "BAG.L", sector: "Consumer Discretionary" },
  { ticker: "AJB.L", sector: "Financials" },
  { ticker: "BWY.L", sector: "Consumer Discretionary" },
  { ticker: "BHMG.L", sector: "Financials" },
  { ticker: "BYG.L", sector: "Real Estate" },
  { ticker: "BPCR.L", sector: "Financials" },
  { ticker: "BRGE.L", sector: "Financials" },
  { ticker: "BRSC.L", sector: "Financials" },
  { ticker: "BRWM.L", sector: "Financials" },
  { ticker: "BSIF.L", sector: "Financials" },
  { ticker: "BOY.L", sector: "Industrials" },
  { ticker: "BREE.L", sector: "Industrials" },
  { ticker: "BPT.L", sector: "Financials" },
  { ticker: "BUT.L", sector: "Financials" },
  { ticker: "BYIT.L", sector: "Industrials" },
  { ticker: "CCR.L", sector: "Consumer Discretionary" },
  { ticker: "CLDN.L", sector: "Financials" },
  { ticker: "CGT.L", sector: "Financials" },
  { ticker: "CCL.L", sector: "Consumer Discretionary" },
  { ticker: "CWR.L", sector: "Energy" },
  { ticker: "CHG.L", sector: "Industrials" },
  { ticker: "CSN.L", sector: "Financials" },
  { ticker: "CHRY.L", sector: "Financials" },
  { ticker: "CTY.L", sector: "Financials" },
  { ticker: "CKN.L", sector: "Industrials" },
  { ticker: "CBG.L", sector: "Financials" },
  { ticker: "CMCX.L", sector: "Financials" },
  { ticker: "COA.L", sector: "Consumer Staples" },
  { ticker: "CCC.L", sector: "Information Technology" },
  { ticker: "COST.L", sector: "Industrials" },
  { ticker: "CWK.L", sector: "Consumer Staples" },
  { ticker: "CURY.L", sector: "Consumer Discretionary" },
  { ticker: "CVSG.L", sector: "Health Care" },
  { ticker: "DLN.L", sector: "Real Estate" },
  { ticker: "DSCV.L", sector: "Industrials" },
  { ticker: "DOM.L", sector: "Consumer Discretionary" },
  { ticker: "DRX.L", sector: "Energy" },
  { ticker: "DOCS.L", sector: "Consumer Discretionary" },
  { ticker: "DNLM.L", sector: "Consumer Discretionary" },
  { ticker: "EZJ.L", sector: "Consumer Discretionary" },
  { ticker: "EDIN.L", sector: "Financials" },
  { ticker: "EWI.L", sector: "Financials" },
  { ticker: "ELM.L", sector: "Materials" },
  { ticker: "ENOG.L", sector: "Energy" },
  { ticker: "ESCT.L", sector: "Financials" },
  { ticker: "EWG.L", sector: "Financials" },
  { ticker: "FCSS.L", sector: "Financials" },
  { ticker: "FEML.L", sector: "Financials" },
  { ticker: "FEV.L", sector: "Financials" },
  { ticker: "FSV.L", sector: "Financials" },
  { ticker: "FGT.L", sector: "Financials" },
  { ticker: "FGP.L", sector: "Consumer Discretionary" },
  { ticker: "FGEN.L", sector: "Financials" },
  { ticker: "FSG.L", sector: "Financials" },
  { ticker: "FRAS.L", sector: "Consumer Discretionary" },
  { ticker: "FCH.L", sector: "Financials" },
  { ticker: "GFRD.L", sector: "Industrials" },
  { ticker: "GAMA.L", sector: "Communication Services" },
  { ticker: "GBG.L", sector: "Information Technology" },
  { ticker: "GCP.L", sector: "Financials" },
  { ticker: "GEN.L", sector: "Industrials" },
  { ticker: "GNS.L", sector: "Information Technology" },
  { ticker: "GSCT.L", sector: "Financials" },
  { ticker: "GDWN.L", sector: "Industrials" },
  { ticker: "GFTU.L", sector: "Industrials" },
  { ticker: "GRI.L", sector: "Real Estate" },
  { ticker: "GPE.L", sector: "Real Estate" },
  { ticker: "UKW.L", sector: "Utilities" },
  { ticker: "GNC.L", sector: "Consumer Discretionary" },
  { ticker: "GRG.L", sector: "Consumer Discretionary" },
  { ticker: "HMSO.L", sector: "Real Estate" },
  { ticker: "HBR.L", sector: "Energy" },
  { ticker: "HVPE.L", sector: "Financials" },
  { ticker: "HWG.L", sector: "Real Estate" },
  { ticker: "HAS.L", sector: "Industrials" },
  { ticker: "HTWS.L", sector: "Communication Services" },
  { ticker: "HFEL.L", sector: "Financials" },
  { ticker: "HSL.L", sector: "Financials" },
  { ticker: "HRI.L", sector: "Financials" },
  { ticker: "HGT.L", sector: "Financials" },
  { ticker: "HICL.L", sector: "Financials" },
  { ticker: "HIK.L", sector: "Information Technology" },
  { ticker: "HILS.L", sector: "Industrials" },
  { ticker: "HFG.L", sector: "Consumer Staples" },
  { ticker: "HOC.L", sector: "Materials" },
  { ticker: "BOWL.L", sector: "Consumer Discretionary" },
  { ticker: "HTG.L", sector: "Energy" },
  { ticker: "IBST.L", sector: "Industrials" },
  { ticker: "ICGT.L", sector: "Financials" },
  { ticker: "IEM.L", sector: "Financials" },
  { ticker: "INCH.L", sector: "Consumer Discretionary" },
  { ticker: "IHP.L", sector: "Financials" },
  { ticker: "IPF.L", sector: "Financials" },
  { ticker: "INPP.L", sector: "Financials" },
  { ticker: "IWG.L", sector: "Industrials" },
  { ticker: "IAD.L", sector: "Financials" },
  { ticker: "INVP.L", sector: "Financials" },
  { ticker: "IPO.L", sector: "Financials" },
  { ticker: "ITH.L", sector: "Energy" },
  { ticker: "ITV.L", sector: "Communication Services" },
  { ticker: "JMAT.L", sector: "Materials" },
  { ticker: "JSG.L", sector: "Industrials" },
  { ticker: "JAM.L", sector: "Financials" },
  { ticker: "JCH.L", sector: "Financials" },
  { ticker: "JEMI.L", sector: "Financials" },
  { ticker: "JMG.L", sector: "Financials" },
  { ticker: "JEDT.L", sector: "Financials" },
  { ticker: "JEGI.L", sector: "Financials" },
  { ticker: "JGGI.L", sector: "Financials" },
  { ticker: "JII.L", sector: "Financials" },
  { ticker: "JFJ.L", sector: "Financials" },
  { ticker: "JTC.L", sector: "Financials" },
  { ticker: "JUP.L", sector: "Financials" },
  { ticker: "KNOS.L", sector: "Information Technology" },
  { ticker: "KLR.L", sector: "Industrials" },
  { ticker: "KIE.L", sector: "Industrials" },
  { ticker: "LRE.L", sector: "Financials" },
  { ticker: "LWDB.L", sector: "Financials" },
  { ticker: "EMG.L", sector: "Financials" },
  { ticker: "MSLH.L", sector: "Industrials" },
  { ticker: "MEGP.L", sector: "Consumer Discretionary" },
  { ticker: "MRC.L", sector: "Financials" },
  { ticker: "MRCH.L", sector: "Financials" },
  { ticker: "MTRO.L", sector: "Financials" },
  { ticker: "MAB.L", sector: "Consumer Discretionary" },
  { ticker: "MTO.L", sector: "Industrials" },
  { ticker: "GROW.L", sector: "Financials" },
  { ticker: "MNKS.L", sector: "Financials" },
  { ticker: "MONY.L", sector: "Communication Services" },
  { ticker: "MOON.L", sector: "Consumer Discretionary" },
  { ticker: "MGAM.L", sector: "Industrials" },
  { ticker: "MGNS.L", sector: "Industrials" },
  { ticker: "MUT.L", sector: "Financials" },
  { ticker: "MYI.L", sector: "Financials" },
  { ticker: "NBPE.L", sector: "Financials" },
  { ticker: "NCC.L", sector: "Information Technology" },
  { ticker: "N91.L", sector: "Financials" },
  { ticker: "NAS.L", sector: "Financials" },
  { ticker: "OCI.L", sector: "Financials" },
  { ticker: "OCDO.L", sector: "Consumer Discretionary" },
  { ticker: "OSB.L", sector: "Financials" },
  { ticker: "OXB.L", sector: "Information Technology" },
  { ticker: "OXIG.L", sector: "Industrials" },
  { ticker: "ONT.L", sector: "Health Care" },
  { ticker: "PHI.L", sector: "Financials" },
  { ticker: "PAGE.L", sector: "Industrials" },
  { ticker: "PAF.L", sector: "Materials" },
  { ticker: "PINT.L", sector: "Financials" },
  { ticker: "PIN.L", sector: "Financials" },
  { ticker: "PAG.L", sector: "Financials" },
  { ticker: "PEY.L", sector: "Financials" },
  { ticker: "PPET.L", sector: "Financials" },
  { ticker: "PNN.L", sector: "Utilities" },
  { ticker: "PNL.L", sector: "Financials" },
  { ticker: "PETS.L", sector: "Consumer Discretionary" },
  { ticker: "PTEC.L", sector: "Information Technology" },
  { ticker: "PLUS.L", sector: "Financials" },
  { ticker: "PCGH.L", sector: "Financials" },
  { ticker: "POLN.L", sector: "Financials" },
  { ticker: "PPH.L", sector: "Consumer Discretionary" },
  { ticker: "PFD.L", sector: "Consumer Discretionary" },
  { ticker: "PHP.L", sector: "Real Estate" },
  { ticker: "PRN.L", sector: "Consumer Discretionary" },
  { ticker: "QQ.L", sector: "Industrials" },
  { ticker: "QLT.L", sector: "Financials" },
  { ticker: "RNK.L", sector: "Consumer Discretionary" },
  { ticker: "RPI.L", sector: "Information Technology" },
  { ticker: "RAT.L", sector: "Financials" },
  { ticker: "RSW.L", sector: "Industrials" },
  { ticker: "RHIM.L", sector: "Industrials" },
  { ticker: "RCP.L", sector: "Financials" },
  { ticker: "ROR.L", sector: "Industrials" },
  { ticker: "RS1.L", sector: "Industrials" },
  { ticker: "RTW.L", sector: "Financials" },
  { ticker: "RICA.L", sector: "Financials" },
  { ticker: "SAFE.L", sector: "Real Estate" },
  { ticker: "SAGA.L", sector: "Consumer Discretionary" },
  { ticker: "SVS.L", sector: "Real Estate" },
  { ticker: "MNTN.L", sector: "Financials" },
  { ticker: "ATR.L", sector: "Financials" },
  { ticker: "SDP.L", sector: "Financials" },
  { ticker: "SOI.L", sector: "Financials" },
  { ticker: "SAIN.L", sector: "Financials" },
  { ticker: "SEIT.L", sector: "Energy" },
  { ticker: "SNR.L", sector: "Industrials" },
  { ticker: "SEQI.L", sector: "Financials" },
  { ticker: "SRP.L", sector: "Industrials" },
  { ticker: "SHC.L", sector: "Real Estate" },
  { ticker: "SHAW.L", sector: "Financials" },
  { ticker: "SRE.L", sector: "Real Estate" },
  { ticker: "SCT.L", sector: "Information Technology" },
  { ticker: "SPI.L", sector: "Health Care" },
  { ticker: "SSPG.L", sector: "Consumer Discretionary" },
  { ticker: "SUPR.L", sector: "Real Estate" },
  { ticker: "SYNC.L", sector: "Information Technology" },
  { ticker: "THRL.L", sector: "Real Estate" },
  { ticker: "TATE.L", sector: "Consumer Staples" },
  { ticker: "TW.L", sector: "Consumer Discretionary" },
  { ticker: "TBCG.L", sector: "Financials" },
  { ticker: "TEP.L", sector: "Communication Services" },
  { ticker: "TMPL.L", sector: "Financials" },
  { ticker: "TEM.L", sector: "Financials" },
  { ticker: "TRIG.L", sector: "Financials" },
  { ticker: "THG.L", sector: "Consumer Discretionary" },
  { ticker: "TCAP.L", sector: "Industrials" },
  { ticker: "TRN.L", sector: "Industrials" },
  { ticker: "TPK.L", sector: "Industrials" },
  { ticker: "TRY.L", sector: "Financials" },
  { ticker: "TRST.L", sector: "Information Technology" },
  { ticker: "TFIF.L", sector: "Financials" },
  { ticker: "UTG.L", sector: "Real Estate" },
  { ticker: "UEM.L", sector: "Financials" },
  { ticker: "VSVS.L", sector: "Industrials" },
  { ticker: "VCT.L", sector: "Materials" },
  { ticker: "VEIL.L", sector: "Financials" },
  { ticker: "VOF.L", sector: "Financials" },
  { ticker: "VTY.L", sector: "Consumer Discretionary" },
  { ticker: "FAN.L", sector: "Industrials" },
  { ticker: "WOSG.L", sector: "Consumer Discretionary" },
  { ticker: "JDW.L", sector: "Consumer Discretionary" },
  { ticker: "SMWH.L", sector: "Consumer Discretionary" },
  { ticker: "WIX.L", sector: "Consumer Discretionary" },
  { ticker: "WIZZ.L", sector: "Consumer Discretionary" },
  { ticker: "WKP.L", sector: "Real Estate" },
  { ticker: "WWH.L", sector: "Financials" },
  { ticker: "WPP.L", sector: "Communication Services" },
  { ticker: "XPS.L", sector: "Financials" },
  { ticker: "ZIG.L", sector: "Industrials" },
];
