import type { ScreenableCompany } from "@/lib/screener/cac40";

// Full Russell 2000 constituent list sourced from iShares IWM ETF holdings
// (BlackRock, April 2025). The index contains ~2 000 small-cap US stocks;
// acquired or delisted tickers will appear as error rows and can be ignored.
export const RUSSELL2000_COMPANIES: ScreenableCompany[] = [
  { ticker: "BE", sector: "Industrials" },
  { ticker: "CRDO", sector: "Information Technology" },
  { ticker: "FN", sector: "Information Technology" },
  { ticker: "CDE", sector: "Materials" },
  { ticker: "NXT", sector: "Industrials" },
  { ticker: "SATS", sector: "Communication Services" },
  { ticker: "IONQ", sector: "Information Technology" },
  { ticker: "RMBS", sector: "Information Technology" },
  { ticker: "STRL", sector: "Industrials" },
  { ticker: "AEIS", sector: "Information Technology" },
  { ticker: "TTMI", sector: "Information Technology" },
  { ticker: "MOD", sector: "Industrials" },
  { ticker: "SITM", sector: "Information Technology" },
  { ticker: "DY", sector: "Industrials" },
  { ticker: "KTOS", sector: "Industrials" },
  { ticker: "HL", sector: "Materials" },
  { ticker: "FORM", sector: "Information Technology" },
  { ticker: "BBIO", sector: "Health Care" },
  { ticker: "GH", sector: "Health Care" },
  { ticker: "SPXC", sector: "Industrials" },
  { ticker: "VIAV", sector: "Information Technology" },
  { ticker: "ENSG", sector: "Health Care" },
  { ticker: "PL", sector: "Industrials" },
  { ticker: "ARWR", sector: "Health Care" },
  { ticker: "SMTC", sector: "Information Technology" },
  { ticker: "SANM", sector: "Information Technology" },
  { ticker: "GTLS", sector: "Industrials" },
  { ticker: "PRIM", sector: "Industrials" },
  { ticker: "OKLO", sector: "Utilities" },
  { ticker: "IDCC", sector: "Information Technology" },
  { ticker: "AAOI", sector: "Information Technology" },
  { ticker: "AHR", sector: "Real Estate" },
  { ticker: "UMBF", sector: "Financials" },
  { ticker: "MDGL", sector: "Health Care" },
  { ticker: "AGX", sector: "Industrials" },
  { ticker: "APLD", sector: "Information Technology" },
  { ticker: "MOGA", sector: "Industrials" },
  { ticker: "LUMN", sector: "Communication Services" },
  { ticker: "CTRE", sector: "Real Estate" },
  { ticker: "PRAX", sector: "Health Care" },
  { ticker: "FCFS", sector: "Financials" },
  { ticker: "ONB", sector: "Financials" },
  { ticker: "WTS", sector: "Industrials" },
  { ticker: "ESE", sector: "Industrials" },
  { ticker: "ZWS", sector: "Industrials" },
  { ticker: "JXN", sector: "Financials" },
  { ticker: "CYTK", sector: "Health Care" },
  { ticker: "VSAT", sector: "Information Technology" },
  { ticker: "HUT", sector: "Information Technology" },
  { ticker: "SNEX", sector: "Financials" },
  { ticker: "FLR", sector: "Industrials" },
  { ticker: "ENS", sector: "Industrials" },
  { ticker: "AVAV", sector: "Industrials" },
  { ticker: "CMC", sector: "Materials" },
  { ticker: "AXSM", sector: "Health Care" },
  { ticker: "PCVX", sector: "Health Care" },
  { ticker: "SM", sector: "Energy" },
  { ticker: "DOCN", sector: "Information Technology" },
  { ticker: "POWL", sector: "Industrials" },
  { ticker: "IBP", sector: "Consumer Discretionary" },
  { ticker: "UEC", sector: "Energy" },
  { ticker: "GATX", sector: "Industrials" },
  { ticker: "QBTS", sector: "Information Technology" },
  { ticker: "TEX", sector: "Industrials" },
  { ticker: "FSS", sector: "Industrials" },
  { ticker: "SLAB", sector: "Information Technology" },
  { ticker: "ORA", sector: "Utilities" },
  { ticker: "WULF", sector: "Information Technology" },
  { ticker: "JBTM", sector: "Industrials" },
  { ticker: "TRNO", sector: "Real Estate" },
  { ticker: "GKOS", sector: "Health Care" },
  { ticker: "CWAN", sector: "Information Technology" },
  { ticker: "VLY", sector: "Financials" },
  { ticker: "PLXS", sector: "Information Technology" },
  { ticker: "KRYS", sector: "Health Care" },
  { ticker: "HQY", sector: "Health Care" },
  { ticker: "RIOT", sector: "Information Technology" },
  { ticker: "GBCI", sector: "Financials" },
  { ticker: "EPRT", sector: "Real Estate" },
  { ticker: "AROC", sector: "Energy" },
  { ticker: "EAT", sector: "Consumer Discretionary" },
  { ticker: "RHP", sector: "Real Estate" },
  { ticker: "SWX", sector: "Utilities" },
  { ticker: "NE", sector: "Energy" },
  { ticker: "UBSI", sector: "Financials" },
  { ticker: "TMHC", sector: "Consumer Discretionary" },
  { ticker: "PIPR", sector: "Financials" },
  { ticker: "NPO", sector: "Industrials" },
  { ticker: "BTSG", sector: "Health Care" },
  { ticker: "SSRM", sector: "Materials" },
  { ticker: "CIFR", sector: "Information Technology" },
  { ticker: "CORZ", sector: "Information Technology" },
  { ticker: "ESNT", sector: "Financials" },
  { ticker: "VICR", sector: "Industrials" },
  { ticker: "PTGX", sector: "Health Care" },
  { ticker: "TXNM", sector: "Utilities" },
  { ticker: "ACA", sector: "Industrials" },
  { ticker: "POR", sector: "Utilities" },
  { ticker: "HWC", sector: "Financials" },
  { ticker: "ROAD", sector: "Industrials" },
  { ticker: "HIMS", sector: "Health Care" },
  { ticker: "BCPC", sector: "Materials" },
  { ticker: "NJR", sector: "Utilities" },
  { ticker: "KRG", sector: "Real Estate" },
  { ticker: "BKH", sector: "Utilities" },
  { ticker: "VAL", sector: "Energy" },
  { ticker: "RIG", sector: "Energy" },
  { ticker: "UFPI", sector: "Industrials" },
  { ticker: "MAC", sector: "Real Estate" },
  { ticker: "ABCB", sector: "Financials" },
  { ticker: "RGTI", sector: "Information Technology" },
  { ticker: "ALKS", sector: "Health Care" },
  { ticker: "AX", sector: "Financials" },
  { ticker: "LNTH", sector: "Health Care" },
  { ticker: "KGS", sector: "Energy" },
  { ticker: "NUVL", sector: "Health Care" },
  { ticker: "PTCT", sector: "Health Care" },
  { ticker: "GVA", sector: "Industrials" },
  { ticker: "MGY", sector: "Energy" },
  { ticker: "MUR", sector: "Energy" },
  { ticker: "TGTX", sector: "Health Care" },
  { ticker: "SR", sector: "Utilities" },
  { ticker: "OGS", sector: "Utilities" },
  { ticker: "AUB", sector: "Financials" },
  { ticker: "IESC", sector: "Industrials" },
  { ticker: "CNX", sector: "Energy" },
  { ticker: "MATX", sector: "Industrials" },
  { ticker: "CWST", sector: "Industrials" },
  { ticker: "REZI", sector: "Industrials" },
  { ticker: "HASI", sector: "Financials" },
  { ticker: "MYRG", sector: "Industrials" },
  { ticker: "BDC", sector: "Information Technology" },
  { ticker: "COGT", sector: "Health Care" },
  { ticker: "SYRE", sector: "Health Care" },
  { ticker: "UUUU", sector: "Energy" },
  { ticker: "GLNG", sector: "Energy" },
  { ticker: "LBRT", sector: "Energy" },
  { ticker: "SIGI", sector: "Financials" },
  { ticker: "HOMB", sector: "Financials" },
  { ticker: "TERN", sector: "Health Care" },
  { ticker: "KNF", sector: "Materials" },
  { ticker: "ATMU", sector: "Industrials" },
  { ticker: "CRSP", sector: "Health Care" },
  { ticker: "BOOT", sector: "Consumer Discretionary" },
  { ticker: "COMP", sector: "Real Estate" },
  { ticker: "KYMR", sector: "Health Care" },
  { ticker: "JOBY", sector: "Industrials" },
  { ticker: "PECO", sector: "Real Estate" },
  { ticker: "SBRA", sector: "Real Estate" },
  { ticker: "VSEC", sector: "Industrials" },
  { ticker: "RDN", sector: "Financials" },
  { ticker: "BIPC", sector: "Utilities" },
  { ticker: "URBN", sector: "Consumer Discretionary" },
  { ticker: "NOVT", sector: "Information Technology" },
  { ticker: "CRC", sector: "Energy" },
  { ticker: "XENE", sector: "Health Care" },
  { ticker: "YOU", sector: "Information Technology" },
  { ticker: "ASB", sector: "Financials" },
  { ticker: "CSW", sector: "Industrials" },
  { ticker: "MTH", sector: "Consumer Discretionary" },
  { ticker: "MIR", sector: "Information Technology" },
  { ticker: "ACLX", sector: "Health Care" },
  { ticker: "DIOD", sector: "Information Technology" },
  { ticker: "BCO", sector: "Industrials" },
  { ticker: "HCC", sector: "Materials" },
  { ticker: "TCBI", sector: "Financials" },
  { ticker: "RUSHA", sector: "Industrials" },
  { ticker: "OPCH", sector: "Health Care" },
  { ticker: "SKY", sector: "Consumer Discretionary" },
  { ticker: "TDS", sector: "Communication Services" },
  { ticker: "OSIS", sector: "Information Technology" },
  { ticker: "RYTM", sector: "Health Care" },
  { ticker: "MARA", sector: "Information Technology" },
  { ticker: "EBC", sector: "Financials" },
  { ticker: "CNR", sector: "Energy" },
  { ticker: "NWE", sector: "Utilities" },
  { ticker: "OUT", sector: "Real Estate" },
  { ticker: "LGND", sector: "Health Care" },
  { ticker: "ACIW", sector: "Information Technology" },
  { ticker: "FTDR", sector: "Consumer Discretionary" },
  { ticker: "FULT", sector: "Financials" },
  { ticker: "AIR", sector: "Industrials" },
  { ticker: "MWA", sector: "Industrials" },
  { ticker: "AZZ", sector: "Industrials" },
  { ticker: "ACLS", sector: "Information Technology" },
  { ticker: "FLG", sector: "Financials" },
  { ticker: "DAN", sector: "Consumer Discretionary" },
  { ticker: "FFIN", sector: "Financials" },
  { ticker: "KLIC", sector: "Information Technology" },
  { ticker: "FOLD", sector: "Health Care" },
  { ticker: "PRM", sector: "Materials" },
  { ticker: "MRCY", sector: "Industrials" },
  { ticker: "UCB", sector: "Financials" },
  { ticker: "MC", sector: "Financials" },
  { ticker: "ERAS", sector: "Health Care" },
  { ticker: "USAR", sector: "Materials" },
  { ticker: "CNO", sector: "Financials" },
  { ticker: "SKT", sector: "Real Estate" },
  { ticker: "TDW", sector: "Energy" },
  { ticker: "PLUG", sector: "Industrials" },
  { ticker: "SXT", sector: "Materials" },
  { ticker: "KTB", sector: "Consumer Discretionary" },
  { ticker: "VISN", sector: "Information Technology" },
  { ticker: "CSTM", sector: "Materials" },
  { ticker: "INDV", sector: "Health Care" },
  { ticker: "PSMT", sector: "Consumer Staples" },
  { ticker: "CVCO", sector: "Consumer Discretionary" },
  { ticker: "SRRK", sector: "Health Care" },
  { ticker: "BGC", sector: "Financials" },
  { ticker: "SFBS", sector: "Financials" },
  { ticker: "CGON", sector: "Health Care" },
  { ticker: "LRN", sector: "Consumer Discretionary" },
  { ticker: "LTH", sector: "Consumer Discretionary" },
  { ticker: "LMND", sector: "Financials" },
  { ticker: "GSAT", sector: "Communication Services" },
  { ticker: "ENVA", sector: "Financials" },
  { ticker: "INDB", sector: "Financials" },
  { ticker: "ALHC", sector: "Health Care" },
  { ticker: "ANF", sector: "Consumer Discretionary" },
  { ticker: "ITRI", sector: "Information Technology" },
  { ticker: "POWI", sector: "Information Technology" },
  { ticker: "CBT", sector: "Materials" },
  { ticker: "MMSI", sector: "Health Care" },
  { ticker: "GPI", sector: "Consumer Discretionary" },
  { ticker: "LGN", sector: "Industrials" },
  { ticker: "STEP", sector: "Financials" },
  { ticker: "CVLT", sector: "Information Technology" },
  { ticker: "FBP", sector: "Financials" },
  { ticker: "LAUR", sector: "Consumer Discretionary" },
  { ticker: "CELC", sector: "Health Care" },
  { ticker: "IBOC", sector: "Financials" },
  { ticker: "HRI", sector: "Industrials" },
  { ticker: "TPH", sector: "Consumer Discretionary" },
  { ticker: "ABG", sector: "Consumer Discretionary" },
  { ticker: "FELE", sector: "Industrials" },
  { ticker: "RNST", sector: "Financials" },
  { ticker: "WSFS", sector: "Financials" },
  { ticker: "PTEN", sector: "Energy" },
  { ticker: "IRTC", sector: "Health Care" },
  { ticker: "MIRM", sector: "Health Care" },
  { ticker: "TPC", sector: "Industrials" },
  { ticker: "RDNT", sector: "Health Care" },
  { ticker: "IRT", sector: "Real Estate" },
  { ticker: "KAI", sector: "Industrials" },
  { ticker: "UNF", sector: "Industrials" },
  { ticker: "BNL", sector: "Real Estate" },
  { ticker: "APGE", sector: "Health Care" },
  { ticker: "TMDX", sector: "Health Care" },
  { ticker: "SHAK", sector: "Consumer Discretionary" },
  { ticker: "MTRN", sector: "Materials" },
  { ticker: "WHD", sector: "Energy" },
  { ticker: "OII", sector: "Energy" },
  { ticker: "ASO", sector: "Consumer Discretionary" },
  { ticker: "SKYW", sector: "Industrials" },
  { ticker: "CVSA", sector: "Consumer Discretionary" },
  { ticker: "CRNX", sector: "Health Care" },
  { ticker: "NVTS", sector: "Information Technology" },
  { ticker: "CATY", sector: "Financials" },
  { ticker: "HP", sector: "Energy" },
  { ticker: "LEU", sector: "Energy" },
  { ticker: "CDP", sector: "Real Estate" },
  { ticker: "STNE", sector: "Financials" },
  { ticker: "NHI", sector: "Real Estate" },
  { ticker: "GNW", sector: "Financials" },
  { ticker: "CC", sector: "Materials" },
  { ticker: "BMI", sector: "Information Technology" },
  { ticker: "GHC", sector: "Consumer Discretionary" },
  { ticker: "BKU", sector: "Financials" },
  { ticker: "GTX", sector: "Consumer Discretionary" },
  { ticker: "VSCO", sector: "Consumer Discretionary" },
  { ticker: "ZETA", sector: "Information Technology" },
  { ticker: "MMS", sector: "Industrials" },
  { ticker: "PJT", sector: "Financials" },
  { ticker: "SIG", sector: "Consumer Discretionary" },
  { ticker: "TWST", sector: "Health Care" },
  { ticker: "LIVN", sector: "Health Care" },
  { ticker: "GFF", sector: "Industrials" },
  { ticker: "FSLY", sector: "Information Technology" },
  { ticker: "LASR", sector: "Information Technology" },
  { ticker: "MHO", sector: "Consumer Discretionary" },
  { ticker: "RELY", sector: "Financials" },
  { ticker: "CVBF", sector: "Financials" },
  { ticker: "ACHR", sector: "Industrials" },
  { ticker: "UCTT", sector: "Information Technology" },
  { ticker: "AAP", sector: "Consumer Discretionary" },
  { ticker: "STNG", sector: "Energy" },
  { ticker: "SPHR", sector: "Communication Services" },
  { ticker: "KBH", sector: "Consumer Discretionary" },
  { ticker: "KFY", sector: "Industrials" },
  { ticker: "FUL", sector: "Materials" },
  { ticker: "PBF", sector: "Energy" },
  { ticker: "OTTR", sector: "Utilities" },
  { ticker: "AVNT", sector: "Materials" },
  { ticker: "CENX", sector: "Materials" },
  { ticker: "PLMR", sector: "Financials" },
  { ticker: "PI", sector: "Information Technology" },
  { ticker: "AVA", sector: "Utilities" },
  { ticker: "VCTR", sector: "Financials" },
  { ticker: "TVTX", sector: "Health Care" },
  { ticker: "BTU", sector: "Energy" },
  { ticker: "NATL", sector: "Financials" },
  { ticker: "OSCR", sector: "Financials" },
  { ticker: "OPLN", sector: "Industrials" },
  { ticker: "VSH", sector: "Information Technology" },
  { ticker: "CALM", sector: "Consumer Staples" },
  { ticker: "BOX", sector: "Information Technology" },
  { ticker: "SYNA", sector: "Information Technology" },
  { ticker: "SXI", sector: "Industrials" },
  { ticker: "EXPO", sector: "Industrials" },
  { ticker: "CBU", sector: "Financials" },
  { ticker: "ADEA", sector: "Information Technology" },
  { ticker: "HWKN", sector: "Materials" },
  { ticker: "CRGY", sector: "Energy" },
  { ticker: "PATK", sector: "Consumer Discretionary" },
  { ticker: "WSBC", sector: "Financials" },
  { ticker: "FFBC", sector: "Financials" },
  { ticker: "BOH", sector: "Financials" },
  { ticker: "DNTH", sector: "Health Care" },
  { ticker: "SEI", sector: "Energy" },
  { ticker: "CPRX", sector: "Health Care" },
  { ticker: "NMIH", sector: "Financials" },
  { ticker: "BXMT", sector: "Financials" },
  { ticker: "BKD", sector: "Health Care" },
  { ticker: "PARR", sector: "Energy" },
  { ticker: "PII", sector: "Consumer Discretionary" },
  { ticker: "RXO", sector: "Industrials" },
  { ticker: "BCC", sector: "Industrials" },
  { ticker: "AWR", sector: "Utilities" },
  { ticker: "CLSK", sector: "Information Technology" },
  { ticker: "INSW", sector: "Energy" },
  { ticker: "FIBK", sector: "Financials" },
  { ticker: "LUNR", sector: "Industrials" },
  { ticker: "SLG", sector: "Real Estate" },
  { ticker: "SBCF", sector: "Financials" },
  { ticker: "CNK", sector: "Communication Services" },
  { ticker: "SOUN", sector: "Information Technology" },
  { ticker: "QLYS", sector: "Information Technology" },
  { ticker: "CTRI", sector: "Industrials" },
  { ticker: "APLE", sector: "Real Estate" },
  { ticker: "ICUI", sector: "Health Care" },
  { ticker: "KMT", sector: "Industrials" },
  { ticker: "VC", sector: "Consumer Discretionary" },
  { ticker: "WDFC", sector: "Consumer Staples" },
  { ticker: "DORM", sector: "Consumer Discretionary" },
  { ticker: "SFNC", sector: "Financials" },
  { ticker: "GPOR", sector: "Energy" },
  { ticker: "SDRL", sector: "Energy" },
  { ticker: "CPK", sector: "Utilities" },
  { ticker: "VECO", sector: "Information Technology" },
  { ticker: "LXP", sector: "Real Estate" },
  { ticker: "CARG", sector: "Communication Services" },
  { ticker: "MGEE", sector: "Utilities" },
  { ticker: "QTWO", sector: "Information Technology" },
  { ticker: "RUN", sector: "Industrials" },
  { ticker: "PFS", sector: "Financials" },
  { ticker: "ITGR", sector: "Health Care" },
  { ticker: "TOWN", sector: "Financials" },
  { ticker: "GPGI", sector: "Information Technology" },
  { ticker: "AEO", sector: "Consumer Discretionary" },
  { ticker: "MRX", sector: "Financials" },
  { ticker: "PLAB", sector: "Information Technology" },
  { ticker: "BEAM", sector: "Health Care" },
  { ticker: "TNGX", sector: "Health Care" },
  { ticker: "CAKE", sector: "Consumer Discretionary" },
  { ticker: "DAVE", sector: "Financials" },
  { ticker: "UNFI", sector: "Consumer Staples" },
  { ticker: "LCII", sector: "Consumer Discretionary" },
  { ticker: "CWT", sector: "Utilities" },
  { ticker: "UPST", sector: "Financials" },
  { ticker: "DBRG", sector: "Financials" },
  { ticker: "MGRC", sector: "Industrials" },
  { ticker: "BELFB", sector: "Information Technology" },
  { ticker: "HGV", sector: "Consumer Discretionary" },
  { ticker: "WAFD", sector: "Financials" },
  { ticker: "MXL", sector: "Information Technology" },
  { ticker: "HAE", sector: "Health Care" },
  { ticker: "AEHR", sector: "Information Technology" },
  { ticker: "AKR", sector: "Real Estate" },
  { ticker: "ACAD", sector: "Health Care" },
  { ticker: "UE", sector: "Real Estate" },
  { ticker: "VRNS", sector: "Information Technology" },
  { ticker: "PHIN", sector: "Consumer Discretionary" },
  { ticker: "SUPN", sector: "Health Care" },
  { ticker: "BBT", sector: "Financials" },
  { ticker: "ACMR", sector: "Information Technology" },
  { ticker: "PBH", sector: "Health Care" },
  { ticker: "CURB", sector: "Real Estate" },
  { ticker: "DNLI", sector: "Health Care" },
  { ticker: "WAY", sector: "Health Care" },
  { ticker: "PRVA", sector: "Health Care" },
  { ticker: "SHOO", sector: "Consumer Discretionary" },
  { ticker: "RRR", sector: "Consumer Discretionary" },
  { ticker: "GOLF", sector: "Consumer Discretionary" },
  { ticker: "ARCB", sector: "Industrials" },
  { ticker: "NGVT", sector: "Materials" },
  { ticker: "DX", sector: "Financials" },
  { ticker: "CON", sector: "Health Care" },
  { ticker: "KN", sector: "Information Technology" },
  { ticker: "JOE", sector: "Real Estate" },
  { ticker: "NIC", sector: "Financials" },
  { ticker: "KALU", sector: "Materials" },
  { ticker: "FCPT", sector: "Real Estate" },
  { ticker: "MCY", sector: "Financials" },
  { ticker: "SLNO", sector: "Health Care" },
  { ticker: "WK", sector: "Information Technology" },
  { ticker: "CUBI", sector: "Financials" },
  { ticker: "PFSI", sector: "Financials" },
  { ticker: "ORKA", sector: "Health Care" },
  { ticker: "IVT", sector: "Real Estate" },
  { ticker: "HUBG", sector: "Industrials" },
  { ticker: "HNI", sector: "Industrials" },
  { ticker: "VCYT", sector: "Health Care" },
  { ticker: "NOG", sector: "Energy" },
  { ticker: "IDYA", sector: "Health Care" },
  { ticker: "TBBK", sector: "Financials" },
  { ticker: "CALX", sector: "Information Technology" },
  { ticker: "PRK", sector: "Financials" },
  { ticker: "ADMA", sector: "Health Care" },
  { ticker: "PPTA", sector: "Materials" },
  { ticker: "TRN", sector: "Industrials" },
  { ticker: "CLDX", sector: "Health Care" },
  { ticker: "BANC", sector: "Financials" },
  { ticker: "HE", sector: "Utilities" },
  { ticker: "AMBA", sector: "Information Technology" },
  { ticker: "ARQT", sector: "Health Care" },
  { ticker: "DYN", sector: "Health Care" },
  { ticker: "ANDE", sector: "Consumer Staples" },
  { ticker: "MZTI", sector: "Consumer Staples" },
  { ticker: "TRMK", sector: "Financials" },
  { ticker: "FRME", sector: "Financials" },
  { ticker: "AMPX", sector: "Industrials" },
  { ticker: "NG", sector: "Materials" },
  { ticker: "GEO", sector: "Industrials" },
  { ticker: "OSW", sector: "Consumer Discretionary" },
  { ticker: "MSGE", sector: "Communication Services" },
  { ticker: "LQDA", sector: "Health Care" },
  { ticker: "NMRK", sector: "Real Estate" },
  { ticker: "ABM", sector: "Industrials" },
  { ticker: "APAM", sector: "Financials" },
  { ticker: "VRRM", sector: "Industrials" },
  { ticker: "CPRI", sector: "Consumer Discretionary" },
  { ticker: "ATKR", sector: "Industrials" },
  { ticker: "BANR", sector: "Financials" },
  { ticker: "FBNC", sector: "Financials" },
  { ticker: "IBRX", sector: "Health Care" },
  { ticker: "BWIN", sector: "Financials" },
  { ticker: "TXG", sector: "Health Care" },
  { ticker: "TARS", sector: "Health Care" },
  { ticker: "BHE", sector: "Information Technology" },
  { ticker: "DHT", sector: "Energy" },
  { ticker: "BANF", sector: "Financials" },
  { ticker: "NTB", sector: "Financials" },
  { ticker: "VERA", sector: "Health Care" },
  { ticker: "CHEF", sector: "Consumer Staples" },
  { ticker: "DK", sector: "Energy" },
  { ticker: "FBK", sector: "Financials" },
  { ticker: "LMAT", sector: "Health Care" },
  { ticker: "IMVT", sector: "Health Care" },
  { ticker: "IMNM", sector: "Health Care" },
  { ticker: "NBTB", sector: "Financials" },
  { ticker: "NTCT", sector: "Information Technology" },
  { ticker: "ICHR", sector: "Information Technology" },
  { ticker: "LION", sector: "Communication Services" },
  { ticker: "ROG", sector: "Information Technology" },
  { ticker: "TENB", sector: "Information Technology" },
  { ticker: "DNOW", sector: "Industrials" },
  { ticker: "AMR", sector: "Materials" },
  { ticker: "DFTX", sector: "Health Care" },
  { ticker: "PRDO", sector: "Consumer Discretionary" },
  { ticker: "ATRO", sector: "Industrials" },
  { ticker: "HLIO", sector: "Industrials" },
  { ticker: "CSGS", sector: "Industrials" },
  { ticker: "PLUS", sector: "Information Technology" },
  { ticker: "CLMT", sector: "Energy" },
  { ticker: "EXTR", sector: "Information Technology" },
  { ticker: "COCO", sector: "Consumer Staples" },
  { ticker: "BUSE", sector: "Financials" },
  { ticker: "MTX", sector: "Materials" },
  { ticker: "GRBK", sector: "Consumer Discretionary" },
  { ticker: "WRBY", sector: "Consumer Discretionary" },
  { ticker: "NWN", sector: "Utilities" },
  { ticker: "KNTK", sector: "Energy" },
  { ticker: "BFH", sector: "Financials" },
  { ticker: "DXPE", sector: "Industrials" },
  { ticker: "NSIT", sector: "Information Technology" },
  { ticker: "BATRK", sector: "Communication Services" },
  { ticker: "NHC", sector: "Health Care" },
  { ticker: "RSI", sector: "Consumer Discretionary" },
  { ticker: "EFSC", sector: "Financials" },
  { ticker: "EOSE", sector: "Industrials" },
  { ticker: "STC", sector: "Financials" },
  { ticker: "RLAY", sector: "Health Care" },
  { ticker: "AMSC", sector: "Industrials" },
  { ticker: "DRH", sector: "Real Estate" },
  { ticker: "OFG", sector: "Financials" },
  { ticker: "EWTX", sector: "Health Care" },
  { ticker: "RCUS", sector: "Health Care" },
  { ticker: "WT", sector: "Financials" },
  { ticker: "COHU", sector: "Information Technology" },
  { ticker: "DBD", sector: "Information Technology" },
  { ticker: "DGII", sector: "Information Technology" },
  { ticker: "ALRM", sector: "Information Technology" },
  { ticker: "CWK", sector: "Real Estate" },
  { ticker: "HURN", sector: "Industrials" },
  { ticker: "CXW", sector: "Industrials" },
  { ticker: "XMTR", sector: "Industrials" },
  { ticker: "ADPT", sector: "Health Care" },
  { ticker: "CASH", sector: "Financials" },
  { ticker: "HTO", sector: "Utilities" },
  { ticker: "NEOG", sector: "Health Care" },
  { ticker: "SPSC", sector: "Information Technology" },
  { ticker: "SMR", sector: "Industrials" },
  { ticker: "BLBD", sector: "Industrials" },
  { ticker: "HMN", sector: "Financials" },
  { ticker: "CALY", sector: "Consumer Discretionary" },
  { ticker: "LC", sector: "Financials" },
  { ticker: "ARR", sector: "Financials" },
  { ticker: "BCRX", sector: "Health Care" },
  { ticker: "VAC", sector: "Consumer Discretionary" },
  { ticker: "DCO", sector: "Industrials" },
  { ticker: "BRZE", sector: "Information Technology" },
  { ticker: "UNIT", sector: "Communication Services" },
  { ticker: "SPNT", sector: "Financials" },
  { ticker: "WERN", sector: "Industrials" },
  { ticker: "PTON", sector: "Consumer Discretionary" },
  { ticker: "TALO", sector: "Energy" },
  { ticker: "SGHC", sector: "Consumer Discretionary" },
  { ticker: "NWBI", sector: "Financials" },
  { ticker: "MD", sector: "Health Care" },
  { ticker: "GT", sector: "Consumer Discretionary" },
  { ticker: "EVTC", sector: "Financials" },
  { ticker: "FCF", sector: "Financials" },
  { ticker: "AUPH", sector: "Health Care" },
  { ticker: "SPB", sector: "Consumer Staples" },
  { ticker: "BULL", sector: "Financials" },
  { ticker: "AMRX", sector: "Health Care" },
  { ticker: "ATEN", sector: "Information Technology" },
  { ticker: "CECO", sector: "Industrials" },
  { ticker: "KWR", sector: "Materials" },
  { ticker: "GNL", sector: "Real Estate" },
  { ticker: "EYE", sector: "Consumer Discretionary" },
  { ticker: "CNS", sector: "Financials" },
  { ticker: "IOSP", sector: "Materials" },
  { ticker: "IRON", sector: "Health Care" },
  { ticker: "EPAC", sector: "Industrials" },
  { ticker: "ECPG", sector: "Financials" },
  { ticker: "PAGS", sector: "Financials" },
  { ticker: "SYBT", sector: "Financials" },
  { ticker: "ZD", sector: "Communication Services" },
  { ticker: "GTY", sector: "Real Estate" },
  { ticker: "QUBT", sector: "Information Technology" },
  { ticker: "NNI", sector: "Financials" },
  { ticker: "AAMI", sector: "Financials" },
  { ticker: "SNDX", sector: "Health Care" },
  { ticker: "OCUL", sector: "Health Care" },
  { ticker: "AXGN", sector: "Health Care" },
  { ticker: "SKWD", sector: "Financials" },
  { ticker: "ALG", sector: "Industrials" },
  { ticker: "MGNI", sector: "Communication Services" },
  { ticker: "GRAL", sector: "Health Care" },
  { ticker: "BKE", sector: "Consumer Discretionary" },
  { ticker: "ALMS", sector: "Health Care" },
  { ticker: "SHO", sector: "Real Estate" },
  { ticker: "TNK", sector: "Energy" },
  { ticker: "LTC", sector: "Real Estate" },
  { ticker: "SEM", sector: "Health Care" },
  { ticker: "HLMN", sector: "Industrials" },
  { ticker: "SOC", sector: "Energy" },
  { ticker: "RAMP", sector: "Information Technology" },
  { ticker: "FUN", sector: "Consumer Discretionary" },
  { ticker: "SMA", sector: "Real Estate" },
  { ticker: "NTLA", sector: "Health Care" },
  { ticker: "THR", sector: "Industrials" },
  { ticker: "TIC", sector: "Industrials" },
  { ticker: "NTST", sector: "Real Estate" },
  { ticker: "STEL", sector: "Financials" },
  { ticker: "INVA", sector: "Health Care" },
  { ticker: "VCEL", sector: "Health Care" },
  { ticker: "ELVN", sector: "Health Care" },
  { ticker: "FRSH", sector: "Information Technology" },
  { ticker: "WOR", sector: "Industrials" },
  { ticker: "SONO", sector: "Consumer Discretionary" },
  { ticker: "STBA", sector: "Financials" },
  { ticker: "CHCO", sector: "Financials" },
  { ticker: "SILA", sector: "Real Estate" },
  { ticker: "STOK", sector: "Health Care" },
  { ticker: "ADNT", sector: "Consumer Discretionary" },
  { ticker: "UTI", sector: "Consumer Discretionary" },
  { ticker: "ADUS", sector: "Health Care" },
  { ticker: "KOD", sector: "Health Care" },
  { ticker: "NN", sector: "Information Technology" },
  { ticker: "NBHC", sector: "Financials" },
  { ticker: "VVX", sector: "Industrials" },
  { ticker: "HTH", sector: "Financials" },
  { ticker: "YELP", sector: "Communication Services" },
  { ticker: "NRIX", sector: "Health Care" },
  { ticker: "STRA", sector: "Consumer Discretionary" },
  { ticker: "IPAR", sector: "Consumer Staples" },
  { ticker: "HCI", sector: "Financials" },
  { ticker: "WLY", sector: "Communication Services" },
  { ticker: "HLF", sector: "Consumer Staples" },
  { ticker: "CRVL", sector: "Health Care" },
  { ticker: "KSS", sector: "Consumer Discretionary" },
  { ticker: "PUMP", sector: "Energy" },
  { ticker: "CENTA", sector: "Consumer Staples" },
  { ticker: "BLX", sector: "Financials" },
  { ticker: "OI", sector: "Materials" },
  { ticker: "AGM", sector: "Financials" },
  { ticker: "WD", sector: "Financials" },
  { ticker: "AGYS", sector: "Information Technology" },
  { ticker: "OMCL", sector: "Health Care" },
  { ticker: "BBAI", sector: "Information Technology" },
  { ticker: "TILE", sector: "Industrials" },
  { ticker: "GEF", sector: "Materials" },
  { ticker: "AIN", sector: "Industrials" },
  { ticker: "AORT", sector: "Health Care" },
  { ticker: "PBI", sector: "Industrials" },
  { ticker: "IMAX", sector: "Communication Services" },
  { ticker: "RXRX", sector: "Health Care" },
  { ticker: "CTS", sector: "Information Technology" },
  { ticker: "WTTR", sector: "Energy" },
  { ticker: "PEB", sector: "Real Estate" },
  { ticker: "BORR", sector: "Energy" },
  { ticker: "NESR", sector: "Energy" },
  { ticker: "ECVT", sector: "Materials" },
  { ticker: "AMLX", sector: "Health Care" },
  { ticker: "FLYW", sector: "Financials" },
  { ticker: "DHC", sector: "Real Estate" },
  { ticker: "XHR", sector: "Real Estate" },
  { ticker: "TCBK", sector: "Financials" },
  { ticker: "ARI", sector: "Financials" },
  { ticker: "MQ", sector: "Financials" },
  { ticker: "JBLU", sector: "Industrials" },
  { ticker: "HOPE", sector: "Financials" },
  { ticker: "GABC", sector: "Financials" },
  { ticker: "NSSC", sector: "Information Technology" },
  { ticker: "PACS", sector: "Health Care" },
  { ticker: "EFC", sector: "Financials" },
  { ticker: "TFIN", sector: "Financials" },
  { ticker: "GRC", sector: "Industrials" },
  { ticker: "LEG", sector: "Consumer Discretionary" },
  { ticker: "HCSG", sector: "Industrials" },
  { ticker: "PRLB", sector: "Industrials" },
  { ticker: "CCS", sector: "Consumer Discretionary" },
  { ticker: "GBX", sector: "Industrials" },
  { ticker: "HG", sector: "Financials" },
  { ticker: "VRE", sector: "Real Estate" },
  { ticker: "DCOM", sector: "Financials" },
  { ticker: "OUST", sector: "Information Technology" },
  { ticker: "BTDR", sector: "Information Technology" },
  { ticker: "UFPT", sector: "Health Care" },
  { ticker: "LZB", sector: "Consumer Discretionary" },
  { ticker: "IIPR", sector: "Real Estate" },
  { ticker: "NVRI", sector: "Industrials" },
  { ticker: "MCRI", sector: "Consumer Discretionary" },
  { ticker: "LKFN", sector: "Financials" },
  { ticker: "CAPR", sector: "Health Care" },
  { ticker: "CBZ", sector: "Industrials" },
  { ticker: "PENG", sector: "Information Technology" },
  { ticker: "ANIP", sector: "Health Care" },
  { ticker: "BL", sector: "Information Technology" },
  { ticker: "DEI", sector: "Real Estate" },
  { ticker: "SBH", sector: "Consumer Discretionary" },
  { ticker: "PAYO", sector: "Financials" },
  { ticker: "QCRH", sector: "Financials" },
  { ticker: "AGIO", sector: "Health Care" },
  { ticker: "TNC", sector: "Industrials" },
  { ticker: "IE", sector: "Materials" },
  { ticker: "WWW", sector: "Consumer Discretionary" },
  { ticker: "FIGS", sector: "Consumer Discretionary" },
  { ticker: "AVPT", sector: "Information Technology" },
  { ticker: "ARLO", sector: "Information Technology" },
  { ticker: "USLM", sector: "Materials" },
  { ticker: "BFC", sector: "Financials" },
  { ticker: "VOYG", sector: "Industrials" },
  { ticker: "ARDX", sector: "Health Care" },
  { ticker: "TSHA", sector: "Health Care" },
  { ticker: "FDP", sector: "Consumer Staples" },
  { ticker: "XPRO", sector: "Energy" },
  { ticker: "PDFS", sector: "Information Technology" },
  { ticker: "CMPR", sector: "Industrials" },
  { ticker: "TNDM", sector: "Health Care" },
  { ticker: "HRMY", sector: "Health Care" },
  { ticker: "OBK", sector: "Financials" },
  { ticker: "CNOB", sector: "Financials" },
  { ticker: "SRCE", sector: "Financials" },
  { ticker: "SLVM", sector: "Materials" },
  { ticker: "VTOL", sector: "Energy" },
  { ticker: "TPB", sector: "Consumer Staples" },
  { ticker: "BLKB", sector: "Information Technology" },
  { ticker: "ZYME", sector: "Health Care" },
  { ticker: "PWP", sector: "Financials" },
  { ticker: "KOS", sector: "Energy" },
  { ticker: "ATRC", sector: "Health Care" },
  { ticker: "MLYS", sector: "Health Care" },
  { ticker: "LPG", sector: "Energy" },
  { ticker: "CRI", sector: "Consumer Discretionary" },
  { ticker: "ABR", sector: "Financials" },
  { ticker: "BRSL", sector: "Consumer Discretionary" },
  { ticker: "ASTE", sector: "Industrials" },
  { ticker: "HLX", sector: "Energy" },
  { ticker: "TRVI", sector: "Health Care" },
  { ticker: "DLX", sector: "Industrials" },
  { ticker: "ASTH", sector: "Health Care" },
  { ticker: "REX", sector: "Energy" },
  { ticker: "INOD", sector: "Industrials" },
  { ticker: "LOB", sector: "Financials" },
  { ticker: "REAL", sector: "Consumer Discretionary" },
  { ticker: "DCH", sector: "Consumer Discretionary" },
  { ticker: "PGNY", sector: "Health Care" },
  { ticker: "KW", sector: "Real Estate" },
  { ticker: "IMKTA", sector: "Consumer Staples" },
  { ticker: "SEZL", sector: "Financials" },
  { ticker: "SHLS", sector: "Industrials" },
  { ticker: "ENOV", sector: "Health Care" },
  { ticker: "AHCO", sector: "Health Care" },
  { ticker: "WABC", sector: "Financials" },
  { ticker: "RCAT", sector: "Industrials" },
  { ticker: "SFL", sector: "Energy" },
  { ticker: "MBIN", sector: "Financials" },
  { ticker: "UVV", sector: "Consumer Staples" },
  { ticker: "ARRY", sector: "Industrials" },
  { ticker: "DFIN", sector: "Financials" },
  { ticker: "NEXT", sector: "Energy" },
  { ticker: "UPWK", sector: "Industrials" },
  { ticker: "PRCT", sector: "Health Care" },
  { ticker: "SLDE", sector: "Financials" },
  { ticker: "NVCR", sector: "Health Care" },
  { ticker: "ORC", sector: "Financials" },
  { ticker: "CRK", sector: "Energy" },
  { ticker: "ENVX", sector: "Industrials" },
  { ticker: "WKC", sector: "Energy" },
  { ticker: "NBR", sector: "Energy" },
  { ticker: "WGS", sector: "Health Care" },
  { ticker: "PRG", sector: "Financials" },
  { ticker: "ADTN", sector: "Information Technology" },
  { ticker: "TRIP", sector: "Communication Services" },
  { ticker: "ACT", sector: "Financials" },
  { ticker: "ENR", sector: "Consumer Staples" },
  { ticker: "AESI", sector: "Energy" },
  { ticker: "UMH", sector: "Real Estate" },
  { ticker: "INTA", sector: "Information Technology" },
  { ticker: "PRA", sector: "Financials" },
  { ticker: "ICFI", sector: "Industrials" },
  { ticker: "JJSF", sector: "Consumer Staples" },
  { ticker: "LADR", sector: "Financials" },
  { ticker: "BHVN", sector: "Health Care" },
  { ticker: "FIHL", sector: "Financials" },
  { ticker: "NVAX", sector: "Health Care" },
  { ticker: "PEBO", sector: "Financials" },
  { ticker: "HROW", sector: "Health Care" },
  { ticker: "BKSY", sector: "Industrials" },
  { ticker: "FIVN", sector: "Information Technology" },
  { ticker: "NUVB", sector: "Health Care" },
  { ticker: "GLUE", sector: "Health Care" },
  { ticker: "TTI", sector: "Energy" },
  { ticker: "PZZA", sector: "Consumer Discretionary" },
  { ticker: "GSHD", sector: "Financials" },
  { ticker: "NPKI", sector: "Industrials" },
  { ticker: "UAMY", sector: "Materials" },
  { ticker: "TGLS", sector: "Industrials" },
  { ticker: "ATEC", sector: "Health Care" },
  { ticker: "MLKN", sector: "Industrials" },
  { ticker: "ROCK", sector: "Industrials" },
  { ticker: "WS", sector: "Materials" },
  { ticker: "MBC", sector: "Industrials" },
  { ticker: "SKYT", sector: "Information Technology" },
  { ticker: "XPEL", sector: "Consumer Discretionary" },
  { ticker: "WINA", sector: "Consumer Discretionary" },
  { ticker: "LINC", sector: "Consumer Discretionary" },
  { ticker: "CNMD", sector: "Health Care" },
  { ticker: "IOVA", sector: "Health Care" },
  { ticker: "TNET", sector: "Industrials" },
  { ticker: "HLIT", sector: "Information Technology" },
  { ticker: "NSP", sector: "Industrials" },
  { ticker: "LFST", sector: "Health Care" },
  { ticker: "CCOI", sector: "Communication Services" },
  { ticker: "TMP", sector: "Financials" },
  { ticker: "LILAK", sector: "Communication Services" },
  { ticker: "VRDN", sector: "Health Care" },
  { ticker: "LNN", sector: "Industrials" },
  { ticker: "GIII", sector: "Consumer Discretionary" },
  { ticker: "TRS", sector: "Materials" },
  { ticker: "PRGS", sector: "Information Technology" },
  { ticker: "TWO", sector: "Financials" },
  { ticker: "GCT", sector: "Consumer Discretionary" },
  { ticker: "ALGT", sector: "Industrials" },
  { ticker: "SAFT", sector: "Financials" },
  { ticker: "TROX", sector: "Materials" },
  { ticker: "SGRY", sector: "Health Care" },
  { ticker: "MIAX", sector: "Financials" },
  { ticker: "CSR", sector: "Real Estate" },
  { ticker: "RYZ", sector: "Materials" },
  { ticker: "PAHC", sector: "Health Care" },
  { ticker: "GPRE", sector: "Energy" },
  { ticker: "AAT", sector: "Real Estate" },
  { ticker: "USPH", sector: "Health Care" },
  { ticker: "SCL", sector: "Materials" },
  { ticker: "CIM", sector: "Financials" },
  { ticker: "NAT", sector: "Energy" },
  { ticker: "ALKT", sector: "Information Technology" },
  { ticker: "AVNS", sector: "Health Care" },
  { ticker: "INBX", sector: "Health Care" },
  { ticker: "AI", sector: "Information Technology" },
  { ticker: "TE", sector: "Industrials" },
  { ticker: "UVSP", sector: "Financials" },
  { ticker: "OCFC", sector: "Financials" },
  { ticker: "WLDN", sector: "Industrials" },
  { ticker: "CCB", sector: "Financials" },
  { ticker: "RVLV", sector: "Consumer Discretionary" },
  { ticker: "MFA", sector: "Financials" },
  { ticker: "ALH", sector: "Industrials" },
  { ticker: "SAH", sector: "Consumer Discretionary" },
  { ticker: "SMPL", sector: "Consumer Staples" },
  { ticker: "EYPT", sector: "Health Care" },
  { ticker: "ALNT", sector: "Industrials" },
  { ticker: "OLMA", sector: "Health Care" },
  { ticker: "RAPP", sector: "Health Care" },
  { ticker: "EPC", sector: "Consumer Staples" },
  { ticker: "RDW", sector: "Industrials" },
  { ticker: "PMT", sector: "Financials" },
  { ticker: "RLJ", sector: "Real Estate" },
  { ticker: "LMB", sector: "Industrials" },
  { ticker: "CTBI", sector: "Financials" },
  { ticker: "INVX", sector: "Energy" },
  { ticker: "BY", sector: "Financials" },
  { ticker: "DOLE", sector: "Consumer Staples" },
  { ticker: "PLOW", sector: "Industrials" },
  { ticker: "PCRX", sector: "Health Care" },
  { ticker: "FG", sector: "Financials" },
  { ticker: "TDAY", sector: "Communication Services" },
  { ticker: "UPBD", sector: "Consumer Discretionary" },
  { ticker: "CRVS", sector: "Health Care" },
  { ticker: "AZTA", sector: "Health Care" },
  { ticker: "PDM", sector: "Real Estate" },
  { ticker: "NEO", sector: "Health Care" },
  { ticker: "TDOC", sector: "Health Care" },
  { ticker: "BFLY", sector: "Health Care" },
  { ticker: "AOSL", sector: "Information Technology" },
  { ticker: "WVE", sector: "Health Care" },
  { ticker: "GHM", sector: "Industrials" },
  { ticker: "CDNA", sector: "Health Care" },
  { ticker: "PNTG", sector: "Health Care" },
  { ticker: "COLL", sector: "Health Care" },
  { ticker: "NNE", sector: "Industrials" },
  { ticker: "OSBC", sector: "Financials" },
  { ticker: "TRUP", sector: "Financials" },
  { ticker: "DEA", sector: "Real Estate" },
  { ticker: "EVLV", sector: "Information Technology" },
  { ticker: "PVLA", sector: "Health Care" },
  { ticker: "AVBP", sector: "Health Care" },
  { ticker: "CLOV", sector: "Health Care" },
  { ticker: "DEC", sector: "Energy" },
  { ticker: "APEI", sector: "Consumer Discretionary" },
  { ticker: "FA", sector: "Industrials" },
  { ticker: "URGN", sector: "Health Care" },
  { ticker: "CVI", sector: "Energy" },
  { ticker: "MSEX", sector: "Utilities" },
  { ticker: "VIR", sector: "Health Care" },
  { ticker: "VYX", sector: "Information Technology" },
  { ticker: "CRAI", sector: "Industrials" },
  { ticker: "FMBH", sector: "Financials" },
  { ticker: "FLNG", sector: "Energy" },
  { ticker: "HFWA", sector: "Financials" },
  { ticker: "SBSI", sector: "Financials" },
  { ticker: "TYRA", sector: "Health Care" },
  { ticker: "VRTS", sector: "Financials" },
  { ticker: "PRKS", sector: "Consumer Discretionary" },
  { ticker: "ANAB", sector: "Health Care" },
  { ticker: "WMK", sector: "Consumer Staples" },
  { ticker: "AMAL", sector: "Financials" },
  { ticker: "MBX", sector: "Health Care" },
  { ticker: "GENI", sector: "Consumer Discretionary" },
  { ticker: "HAFC", sector: "Financials" },
  { ticker: "XERS", sector: "Health Care" },
  { ticker: "NX", sector: "Industrials" },
  { ticker: "PCT", sector: "Materials" },
  { ticker: "CFFN", sector: "Financials" },
  { ticker: "JBGS", sector: "Real Estate" },
  { ticker: "SCSC", sector: "Information Technology" },
  { ticker: "OMER", sector: "Health Care" },
  { ticker: "LGIH", sector: "Consumer Discretionary" },
  { ticker: "UTL", sector: "Utilities" },
  { ticker: "UVE", sector: "Financials" },
  { ticker: "NBN", sector: "Financials" },
  { ticker: "BLFS", sector: "Health Care" },
  { ticker: "LIF", sector: "Information Technology" },
  { ticker: "BUR", sector: "Financials" },
  { ticker: "SAFE", sector: "Real Estate" },
  { ticker: "BV", sector: "Industrials" },
  { ticker: "FTRE", sector: "Health Care" },
  { ticker: "AMRC", sector: "Industrials" },
  { ticker: "FLY", sector: "Industrials" },
  { ticker: "FSUN", sector: "Financials" },
  { ticker: "THRM", sector: "Consumer Discretionary" },
  { ticker: "GOLD", sector: "Consumer Discretionary" },
  { ticker: "TRST", sector: "Financials" },
  { ticker: "WGO", sector: "Consumer Discretionary" },
  { ticker: "EIG", sector: "Financials" },
  { ticker: "CCNE", sector: "Financials" },
  { ticker: "AMTB", sector: "Financials" },
  { ticker: "VSTS", sector: "Industrials" },
  { ticker: "AMC", sector: "Communication Services" },
  { ticker: "XNCR", sector: "Health Care" },
  { ticker: "WSR", sector: "Real Estate" },
  { ticker: "ACVA", sector: "Industrials" },
  { ticker: "SCHL", sector: "Communication Services" },
  { ticker: "UFCS", sector: "Financials" },
  { ticker: "BHRB", sector: "Financials" },
  { ticker: "CPF", sector: "Financials" },
  { ticker: "PRSU", sector: "Consumer Discretionary" },
  { ticker: "PAX", sector: "Financials" },
  { ticker: "SHEN", sector: "Communication Services" },
  { ticker: "BFST", sector: "Financials" },
  { ticker: "STAA", sector: "Health Care" },
  { ticker: "CBL", sector: "Real Estate" },
  { ticker: "HBNC", sector: "Financials" },
  { ticker: "COUR", sector: "Consumer Discretionary" },
  { ticker: "APPN", sector: "Information Technology" },
  { ticker: "MRTN", sector: "Industrials" },
  { ticker: "FLNC", sector: "Industrials" },
  { ticker: "PLPC", sector: "Industrials" },
  { ticker: "SNCY", sector: "Industrials" },
  { ticker: "ASST", sector: "Health Care" },
  { ticker: "MATW", sector: "Consumer Discretionary" },
  { ticker: "CAC", sector: "Financials" },
  { ticker: "IDT", sector: "Communication Services" },
  { ticker: "GRDN", sector: "Health Care" },
  { ticker: "ASGN", sector: "Information Technology" },
  { ticker: "ESQ", sector: "Financials" },
  { ticker: "MBWM", sector: "Financials" },
  { ticker: "MNKD", sector: "Health Care" },
  { ticker: "CDRE", sector: "Industrials" },
  { ticker: "VERX", sector: "Information Technology" },
  { ticker: "PGY", sector: "Information Technology" },
  { ticker: "JBIO", sector: "Health Care" },
  { ticker: "GERN", sector: "Health Care" },
  { ticker: "MCB", sector: "Financials" },
  { ticker: "PRAA", sector: "Financials" },
  { ticker: "FIZZ", sector: "Consumer Staples" },
  { ticker: "KODK", sector: "Information Technology" },
  { ticker: "CLB", sector: "Energy" },
  { ticker: "EE", sector: "Energy" },
  { ticker: "NWPX", sector: "Industrials" },
  { ticker: "CMP", sector: "Materials" },
  { ticker: "BRSP", sector: "Financials" },
  { ticker: "MYE", sector: "Materials" },
  { ticker: "LQDT", sector: "Industrials" },
  { ticker: "TR", sector: "Consumer Staples" },
  { ticker: "ANNX", sector: "Health Care" },
  { ticker: "SLS", sector: "Health Care" },
  { ticker: "SMP", sector: "Consumer Discretionary" },
  { ticker: "THFF", sector: "Financials" },
  { ticker: "LXU", sector: "Materials" },
  { ticker: "ESRT", sector: "Real Estate" },
  { ticker: "FWRG", sector: "Consumer Discretionary" },
  { ticker: "FMNB", sector: "Financials" },
  { ticker: "LZ", sector: "Industrials" },
  { ticker: "CNXN", sector: "Information Technology" },
  { ticker: "AMN", sector: "Health Care" },
  { ticker: "BBUC", sector: "Industrials" },
  { ticker: "PKST", sector: "Real Estate" },
  { ticker: "CODI", sector: "Financials" },
  { ticker: "DAKT", sector: "Information Technology" },
  { ticker: "QDEL", sector: "Health Care" },
  { ticker: "AIP", sector: "Information Technology" },
  { ticker: "PFBC", sector: "Financials" },
  { ticker: "APOG", sector: "Industrials" },
  { ticker: "AMPH", sector: "Health Care" },
  { ticker: "FBRT", sector: "Financials" },
  { ticker: "NBBK", sector: "Financials" },
  { ticker: "HTB", sector: "Financials" },
  { ticker: "GBTG", sector: "Consumer Discretionary" },
  { ticker: "BBSI", sector: "Industrials" },
  { ticker: "MCHB", sector: "Financials" },
  { ticker: "KURA", sector: "Health Care" },
  { ticker: "GNK", sector: "Industrials" },
  { ticker: "ZGN", sector: "Consumer Discretionary" },
  { ticker: "BJRI", sector: "Consumer Discretionary" },
  { ticker: "TALK", sector: "Health Care" },
  { ticker: "DRVN", sector: "Consumer Discretionary" },
  { ticker: "KALV", sector: "Health Care" },
  { ticker: "EGBN", sector: "Financials" },
  { ticker: "CMRE", sector: "Industrials" },
  { ticker: "NPK", sector: "Industrials" },
  { ticker: "GO", sector: "Consumer Staples" },
  { ticker: "TRNS", sector: "Industrials" },
  { ticker: "RWT", sector: "Financials" },
  { ticker: "BCAX", sector: "Health Care" },
  { ticker: "JBI", sector: "Industrials" },
  { ticker: "FOXF", sector: "Consumer Discretionary" },
  { ticker: "BKV", sector: "Energy" },
  { ticker: "SVRA", sector: "Health Care" },
  { ticker: "KOP", sector: "Materials" },
  { ticker: "IRMD", sector: "Health Care" },
  { ticker: "EQBK", sector: "Financials" },
  { ticker: "PGEN", sector: "Health Care" },
  { ticker: "STGW", sector: "Communication Services" },
  { ticker: "LIND", sector: "Consumer Discretionary" },
  { ticker: "ODC", sector: "Consumer Staples" },
  { ticker: "HTZ", sector: "Industrials" },
  { ticker: "MCW", sector: "Consumer Discretionary" },
  { ticker: "CSV", sector: "Consumer Discretionary" },
  { ticker: "VPG", sector: "Information Technology" },
  { ticker: "MMI", sector: "Real Estate" },
  { ticker: "CGEM", sector: "Health Care" },
  { ticker: "NTGR", sector: "Information Technology" },
  { ticker: "RUM", sector: "Communication Services" },
  { ticker: "HRTG", sector: "Financials" },
  { ticker: "IART", sector: "Health Care" },
  { ticker: "MEG", sector: "Industrials" },
  { ticker: "ORIC", sector: "Health Care" },
  { ticker: "QNST", sector: "Communication Services" },
  { ticker: "FCBC", sector: "Financials" },
  { ticker: "SG", sector: "Consumer Discretionary" },
  { ticker: "RES", sector: "Energy" },
  { ticker: "IBCP", sector: "Financials" },
  { ticker: "ORRF", sector: "Financials" },
  { ticker: "EHAB", sector: "Health Care" },
  { ticker: "MAZE", sector: "Health Care" },
  { ticker: "CSTL", sector: "Health Care" },
  { ticker: "MTUS", sector: "Materials" },
  { ticker: "SWBI", sector: "Consumer Discretionary" },
  { ticker: "INDI", sector: "Information Technology" },
  { ticker: "PRCH", sector: "Information Technology" },
  { ticker: "TK", sector: "Energy" },
  { ticker: "CMPX", sector: "Health Care" },
  { ticker: "SMBC", sector: "Financials" },
  { ticker: "ROOT", sector: "Financials" },
  { ticker: "GDOT", sector: "Financials" },
  { ticker: "FISI", sector: "Financials" },
  { ticker: "MPB", sector: "Financials" },
  { ticker: "IVR", sector: "Financials" },
  { ticker: "ADAM", sector: "Financials" },
  { ticker: "NB", sector: "Materials" },
  { ticker: "PSIX", sector: "Industrials" },
  { ticker: "DJCO", sector: "Information Technology" },
  { ticker: "RUSHB", sector: "Industrials" },
  { ticker: "KE", sector: "Information Technology" },
  { ticker: "FSBC", sector: "Financials" },
  { ticker: "MCBS", sector: "Financials" },
  { ticker: "SABR", sector: "Consumer Discretionary" },
  { ticker: "SVC", sector: "Real Estate" },
  { ticker: "CBRL", sector: "Consumer Discretionary" },
  { ticker: "OXM", sector: "Consumer Discretionary" },
  { ticker: "RBCAA", sector: "Financials" },
  { ticker: "CCBG", sector: "Financials" },
  { ticker: "BAND", sector: "Communication Services" },
  { ticker: "AMPL", sector: "Information Technology" },
  { ticker: "JANX", sector: "Health Care" },
  { ticker: "AMWD", sector: "Industrials" },
  { ticker: "GCMG", sector: "Financials" },
  { ticker: "EGY", sector: "Energy" },
  { ticker: "ABUS", sector: "Health Care" },
  { ticker: "SLDP", sector: "Consumer Discretionary" },
  { ticker: "SDGR", sector: "Health Care" },
  { ticker: "PGC", sector: "Financials" },
  { ticker: "FET", sector: "Energy" },
  { ticker: "CEVA", sector: "Information Technology" },
  { ticker: "SENEA", sector: "Consumer Staples" },
  { ticker: "RYAM", sector: "Materials" },
  { ticker: "SION", sector: "Health Care" },
  { ticker: "SMBK", sector: "Financials" },
  { ticker: "TBPH", sector: "Health Care" },
  { ticker: "LYTS", sector: "Industrials" },
  { ticker: "CTLP", sector: "Financials" },
  { ticker: "STKL", sector: "Consumer Staples" },
  { ticker: "JBSS", sector: "Consumer Staples" },
  { ticker: "NAVI", sector: "Financials" },
  { ticker: "IDR", sector: "Materials" },
  { ticker: "ACEL", sector: "Consumer Discretionary" },
  { ticker: "MITK", sector: "Information Technology" },
  { ticker: "AEVA", sector: "Information Technology" },
  { ticker: "BZH", sector: "Consumer Discretionary" },
  { ticker: "ASIX", sector: "Materials" },
  { ticker: "OIS", sector: "Energy" },
  { ticker: "CRML", sector: "Materials" },
  { ticker: "SERV", sector: "Consumer Discretionary" },
  { ticker: "AMBQ", sector: "Information Technology" },
  { ticker: "HTFL", sector: "Health Care" },
  { ticker: "IRWD", sector: "Health Care" },
  { ticker: "RHLD", sector: "Industrials" },
  { ticker: "DRUG", sector: "Health Care" },
  { ticker: "ASPI", sector: "Materials" },
  { ticker: "AROW", sector: "Financials" },
  { ticker: "KOPN", sector: "Information Technology" },
  { ticker: "SBGI", sector: "Communication Services" },
  { ticker: "SHBI", sector: "Financials" },
  { ticker: "YSS", sector: "Industrials" },
  { ticker: "FIP", sector: "Industrials" },
  { ticker: "TRTX", sector: "Financials" },
  { ticker: "NVGS", sector: "Energy" },
  { ticker: "CTO", sector: "Real Estate" },
  { ticker: "CASS", sector: "Financials" },
  { ticker: "NXRT", sector: "Real Estate" },
  { ticker: "KMTS", sector: "Health Care" },
  { ticker: "LBRX", sector: "Health Care" },
  { ticker: "CABO", sector: "Communication Services" },
  { ticker: "NAVN", sector: "Consumer Discretionary" },
  { ticker: "PKE", sector: "Industrials" },
  { ticker: "GOOD", sector: "Real Estate" },
  { ticker: "ETON", sector: "Health Care" },
  { ticker: "ALRS", sector: "Financials" },
  { ticker: "RGR", sector: "Consumer Discretionary" },
  { ticker: "ARVN", sector: "Health Care" },
  { ticker: "AMSF", sector: "Financials" },
  { ticker: "EXPI", sector: "Real Estate" },
  { ticker: "WASH", sector: "Financials" },
  { ticker: "HOV", sector: "Consumer Discretionary" },
  { ticker: "SANA", sector: "Health Care" },
  { ticker: "METC", sector: "Materials" },
  { ticker: "AVO", sector: "Consumer Staples" },
  { ticker: "SATL", sector: "Industrials" },
  { ticker: "HZO", sector: "Consumer Discretionary" },
  { ticker: "RZLV", sector: "Information Technology" },
  { ticker: "CARS", sector: "Communication Services" },
  { ticker: "ERII", sector: "Industrials" },
  { ticker: "KFRC", sector: "Industrials" },
  { ticker: "GSBC", sector: "Financials" },
  { ticker: "ASC", sector: "Energy" },
  { ticker: "BHB", sector: "Financials" },
  { ticker: "SEMR", sector: "Information Technology" },
  { ticker: "CBLL", sector: "Health Care" },
  { ticker: "NUTX", sector: "Health Care" },
  { ticker: "ZVRA", sector: "Health Care" },
  { ticker: "SPFI", sector: "Financials" },
  { ticker: "CXM", sector: "Information Technology" },
  { ticker: "PHAT", sector: "Health Care" },
  { ticker: "CRMD", sector: "Health Care" },
  { ticker: "FOR", sector: "Real Estate" },
  { ticker: "UTZ", sector: "Consumer Staples" },
  { ticker: "RIGL", sector: "Health Care" },
  { ticker: "MPLT", sector: "Health Care" },
  { ticker: "PD", sector: "Information Technology" },
  { ticker: "AMBP", sector: "Materials" },
  { ticker: "NRIM", sector: "Financials" },
  { ticker: "GDEN", sector: "Consumer Discretionary" },
  { ticker: "HELE", sector: "Consumer Discretionary" },
  { ticker: "CNNE", sector: "Financials" },
  { ticker: "CARE", sector: "Financials" },
  { ticker: "EMBC", sector: "Health Care" },
  { ticker: "BLMN", sector: "Consumer Discretionary" },
  { ticker: "REPX", sector: "Energy" },
  { ticker: "ALX", sector: "Real Estate" },
  { ticker: "TREE", sector: "Financials" },
  { ticker: "ABSI", sector: "Health Care" },
  { ticker: "HNRG", sector: "Utilities" },
  { ticker: "WLFC", sector: "Industrials" },
  { ticker: "PAR", sector: "Information Technology" },
  { ticker: "TCMD", sector: "Health Care" },
  { ticker: "CTOS", sector: "Industrials" },
  { ticker: "PFIS", sector: "Financials" },
  { ticker: "SEPN", sector: "Health Care" },
  { ticker: "VTS", sector: "Energy" },
  { ticker: "UHT", sector: "Real Estate" },
  { ticker: "SXC", sector: "Materials" },
  { ticker: "ASAN", sector: "Information Technology" },
  { ticker: "GLRE", sector: "Financials" },
  { ticker: "CPS", sector: "Consumer Discretionary" },
  { ticker: "MLR", sector: "Industrials" },
  { ticker: "INN", sector: "Real Estate" },
  { ticker: "CWCO", sector: "Utilities" },
  { ticker: "BTBT", sector: "Information Technology" },
  { ticker: "PSTL", sector: "Real Estate" },
  { ticker: "MAMA", sector: "Consumer Staples" },
  { ticker: "MATV", sector: "Materials" },
  { ticker: "BIOA", sector: "Health Care" },
  { ticker: "SIBN", sector: "Health Care" },
  { ticker: "HTLD", sector: "Industrials" },
  { ticker: "FFIC", sector: "Financials" },
  { ticker: "MNRO", sector: "Consumer Discretionary" },
  { ticker: "PHR", sector: "Health Care" },
  { ticker: "ETD", sector: "Consumer Discretionary" },
  { ticker: "DC", sector: "Materials" },
  { ticker: "HIPO", sector: "Financials" },
  { ticker: "TCBX", sector: "Financials" },
  { ticker: "VREX", sector: "Health Care" },
  { ticker: "GTN", sector: "Communication Services" },
  { ticker: "SPIR", sector: "Industrials" },
  { ticker: "GSM", sector: "Materials" },
  { ticker: "CTKB", sector: "Health Care" },
  { ticker: "NFBK", sector: "Financials" },
  { ticker: "OPK", sector: "Health Care" },
  { ticker: "ACNB", sector: "Financials" },
  { ticker: "MLAB", sector: "Health Care" },
  { ticker: "BDN", sector: "Real Estate" },
  { ticker: "HSTM", sector: "Health Care" },
  { ticker: "CWBC", sector: "Financials" },
  { ticker: "FLOC", sector: "Energy" },
  { ticker: "SD", sector: "Energy" },
  { ticker: "FWRD", sector: "Industrials" },
  { ticker: "CVLG", sector: "Industrials" },
  { ticker: "ATEX", sector: "Communication Services" },
  { ticker: "HY", sector: "Industrials" },
  { ticker: "IIIV", sector: "Information Technology" },
  { ticker: "SPRY", sector: "Health Care" },
  { ticker: "CYRX", sector: "Health Care" },
  { ticker: "BETA", sector: "Industrials" },
  { ticker: "CCSI", sector: "Information Technology" },
  { ticker: "AHRT", sector: "Real Estate" },
  { ticker: "IHRT", sector: "Communication Services" },
  { ticker: "CLBK", sector: "Financials" },
  { ticker: "MBUU", sector: "Consumer Discretionary" },
  { ticker: "CDNL", sector: "Industrials" },
  { ticker: "BSRR", sector: "Financials" },
  { ticker: "SLDB", sector: "Health Care" },
  { ticker: "EBF", sector: "Industrials" },
  { ticker: "GIC", sector: "Industrials" },
  { ticker: "CIVB", sector: "Financials" },
  { ticker: "PRTA", sector: "Health Care" },
  { ticker: "FBIZ", sector: "Financials" },
  { ticker: "OFIX", sector: "Health Care" },
  { ticker: "CAL", sector: "Consumer Discretionary" },
  { ticker: "CHCT", sector: "Real Estate" },
  { ticker: "HIFS", sector: "Financials" },
  { ticker: "ORN", sector: "Industrials" },
  { ticker: "FULC", sector: "Health Care" },
  { ticker: "MSBI", sector: "Financials" },
  { ticker: "IIIN", sector: "Industrials" },
  { ticker: "CVGW", sector: "Consumer Staples" },
  { ticker: "ARKO", sector: "Consumer Discretionary" },
  { ticker: "FPI", sector: "Real Estate" },
  { ticker: "MTW", sector: "Industrials" },
  { ticker: "OMDA", sector: "Health Care" },
  { ticker: "BBW", sector: "Consumer Discretionary" },
  { ticker: "TITN", sector: "Industrials" },
  { ticker: "DFH", sector: "Consumer Discretionary" },
  { ticker: "XRN", sector: "Real Estate" },
  { ticker: "ESPR", sector: "Health Care" },
  { ticker: "RRBI", sector: "Financials" },
  { ticker: "CMCO", sector: "Industrials" },
  { ticker: "HPP", sector: "Real Estate" },
  { ticker: "NATR", sector: "Consumer Staples" },
  { ticker: "SFST", sector: "Financials" },
  { ticker: "RPC", sector: "Financials" },
  { ticker: "BVS", sector: "Health Care" },
  { ticker: "TH", sector: "Consumer Discretionary" },
  { ticker: "KRNY", sector: "Financials" },
  { ticker: "UDMY", sector: "Consumer Discretionary" },
  { ticker: "BWMN", sector: "Industrials" },
  { ticker: "IMXI", sector: "Financials" },
  { ticker: "OBT", sector: "Financials" },
  { ticker: "BBNX", sector: "Health Care" },
  { ticker: "HBCP", sector: "Financials" },
  { ticker: "BXC", sector: "Industrials" },
  { ticker: "MOV", sector: "Consumer Discretionary" },
  { ticker: "MYGN", sector: "Health Care" },
  { ticker: "OPTU", sector: "Communication Services" },
  { ticker: "JCAP", sector: "Financials" },
  { ticker: "EVER", sector: "Communication Services" },
  { ticker: "RDVT", sector: "Information Technology" },
  { ticker: "SSTK", sector: "Communication Services" },
  { ticker: "PACB", sector: "Health Care" },
  { ticker: "AIOT", sector: "Information Technology" },
  { ticker: "PTLO", sector: "Consumer Discretionary" },
  { ticker: "VITL", sector: "Consumer Staples" },
  { ticker: "AEBI", sector: "Industrials" },
  { ticker: "COFS", sector: "Financials" },
  { ticker: "PLSE", sector: "Health Care" },
  { ticker: "NPCE", sector: "Health Care" },
  { ticker: "OSPN", sector: "Information Technology" },
  { ticker: "MCS", sector: "Communication Services" },
  { ticker: "ZBIO", sector: "Health Care" },
  { ticker: "RR", sector: "Industrials" },
  { ticker: "NRDS", sector: "Financials" },
  { ticker: "MGTX", sector: "Health Care" },
  { ticker: "ATLC", sector: "Financials" },
  { ticker: "SFIX", sector: "Consumer Discretionary" },
  { ticker: "GEVO", sector: "Energy" },
  { ticker: "RGNX", sector: "Health Care" },
  { ticker: "TIPT", sector: "Financials" },
  { ticker: "AKTS", sector: "Health Care" },
  { ticker: "AVR", sector: "Health Care" },
  { ticker: "EBS", sector: "Health Care" },
  { ticker: "ACRS", sector: "Health Care" },
  { ticker: "BOW", sector: "Financials" },
  { ticker: "RBB", sector: "Financials" },
  { ticker: "ANGO", sector: "Health Care" },
  { ticker: "TDUP", sector: "Consumer Discretionary" },
  { ticker: "FDMT", sector: "Health Care" },
  { ticker: "CWH", sector: "Consumer Discretionary" },
  { ticker: "OLP", sector: "Real Estate" },
  { ticker: "CLDT", sector: "Real Estate" },
  { ticker: "GEFB", sector: "Materials" },
  { ticker: "TRC", sector: "Real Estate" },
  { ticker: "AQST", sector: "Health Care" },
  { ticker: "GRND", sector: "Communication Services" },
  { ticker: "CMCL", sector: "Materials" },
  { ticker: "VSTM", sector: "Health Care" },
  { ticker: "CLNE", sector: "Energy" },
  { ticker: "ABAT", sector: "Materials" },
  { ticker: "IPI", sector: "Materials" },
  { ticker: "BATRA", sector: "Communication Services" },
  { ticker: "OEC", sector: "Materials" },
  { ticker: "BGS", sector: "Consumer Staples" },
  { ticker: "BCAL", sector: "Financials" },
  { ticker: "YORW", sector: "Utilities" },
  { ticker: "IBTA", sector: "Communication Services" },
  { ticker: "MDXG", sector: "Health Care" },
  { ticker: "TTAM", sector: "Materials" },
  { ticker: "ILPT", sector: "Real Estate" },
  { ticker: "LXEO", sector: "Health Care" },
  { ticker: "DIN", sector: "Consumer Discretionary" },
  { ticker: "UNTY", sector: "Financials" },
  { ticker: "MVST", sector: "Industrials" },
  { ticker: "ADCT", sector: "Health Care" },
  { ticker: "PRME", sector: "Health Care" },
  { ticker: "BFS", sector: "Real Estate" },
  { ticker: "WTBA", sector: "Financials" },
  { ticker: "BWB", sector: "Financials" },
  { ticker: "BYND", sector: "Consumer Staples" },
  { ticker: "YEXT", sector: "Information Technology" },
  { ticker: "TWI", sector: "Industrials" },
  { ticker: "OOMA", sector: "Information Technology" },
  { ticker: "LOCO", sector: "Consumer Discretionary" },
  { ticker: "VLGEA", sector: "Consumer Staples" },
  { ticker: "AVIR", sector: "Health Care" },
  { ticker: "NGS", sector: "Energy" },
  { ticker: "GDYN", sector: "Information Technology" },
  { ticker: "BBBY", sector: "Consumer Discretionary" },
  { ticker: "ARHS", sector: "Consumer Discretionary" },
  { ticker: "BELFA", sector: "Information Technology" },
  { ticker: "MH", sector: "Consumer Discretionary" },
  { ticker: "RPD", sector: "Information Technology" },
  { ticker: "KRUS", sector: "Consumer Discretionary" },
  { ticker: "BMRC", sector: "Financials" },
  { ticker: "CBAN", sector: "Financials" },
  { ticker: "LTBR", sector: "Energy" },
  { ticker: "CBNK", sector: "Financials" },
  { ticker: "WTI", sector: "Energy" },
  { ticker: "MRVI", sector: "Health Care" },
  { ticker: "WRLD", sector: "Financials" },
  { ticker: "RNGR", sector: "Energy" },
  { ticker: "VNDA", sector: "Health Care" },
  { ticker: "APPS", sector: "Information Technology" },
  { ticker: "CENT", sector: "Consumer Staples" },
  { ticker: "MCFT", sector: "Consumer Discretionary" },
  { ticker: "GRPN", sector: "Consumer Discretionary" },
  { ticker: "FRBA", sector: "Financials" },
  { ticker: "CZNC", sector: "Financials" },
  { ticker: "ABX", sector: "Financials" },
  { ticker: "FMAO", sector: "Financials" },
  { ticker: "NVEC", sector: "Information Technology" },
  { ticker: "ALT", sector: "Health Care" },
  { ticker: "NUS", sector: "Consumer Staples" },
  { ticker: "ENTA", sector: "Health Care" },
  { ticker: "RM", sector: "Financials" },
  { ticker: "HSHP", sector: "Industrials" },
  { ticker: "TRDA", sector: "Health Care" },
  { ticker: "ALLO", sector: "Health Care" },
  { ticker: "EU", sector: "Energy" },
  { ticker: "HBT", sector: "Financials" },
  { ticker: "REAX", sector: "Real Estate" },
  { ticker: "WNC", sector: "Industrials" },
  { ticker: "AKBA", sector: "Health Care" },
  { ticker: "BWFG", sector: "Financials" },
  { ticker: "TSSI", sector: "Information Technology" },
  { ticker: "AVAH", sector: "Health Care" },
  { ticker: "GCO", sector: "Consumer Discretionary" },
  { ticker: "ITIC", sector: "Financials" },
  { ticker: "CRNC", sector: "Information Technology" },
  { ticker: "FUBO", sector: "Communication Services" },
  { ticker: "NABL", sector: "Information Technology" },
  { ticker: "TRAX", sector: "Health Care" },
  { ticker: "PLAY", sector: "Consumer Discretionary" },
  { ticker: "CERS", sector: "Health Care" },
  { ticker: "FVR", sector: "Real Estate" },
  { ticker: "XOMA", sector: "Health Care" },
  { ticker: "PUBM", sector: "Communication Services" },
  { ticker: "CLFD", sector: "Information Technology" },
  { ticker: "WLTH", sector: "Financials" },
  { ticker: "LAND", sector: "Real Estate" },
  { ticker: "FEIM", sector: "Information Technology" },
  { ticker: "SCVL", sector: "Consumer Discretionary" },
  { ticker: "NGVC", sector: "Consumer Staples" },
  { ticker: "FNLC", sector: "Financials" },
  { ticker: "INV", sector: "Financials" },
  { ticker: "NPB", sector: "Financials" },
  { ticker: "GOGO", sector: "Communication Services" },
  { ticker: "PDLB", sector: "Financials" },
  { ticker: "CLMB", sector: "Information Technology" },
  { ticker: "PKBK", sector: "Financials" },
  { ticker: "KREF", sector: "Financials" },
  { ticker: "KROS", sector: "Health Care" },
  { ticker: "NXDR", sector: "Communication Services" },
  { ticker: "SB", sector: "Industrials" },
  { ticker: "LXFR", sector: "Industrials" },
  { ticker: "CTGO", sector: "Materials" },
  { ticker: "MAGN", sector: "Materials" },
  { ticker: "BCML", sector: "Financials" },
  { ticker: "MTRX", sector: "Industrials" },
  { ticker: "STRT", sector: "Consumer Discretionary" },
  { ticker: "EVH", sector: "Health Care" },
  { ticker: "NEWT", sector: "Financials" },
  { ticker: "SRTA", sector: "Health Care" },
  { ticker: "ZUMZ", sector: "Consumer Discretionary" },
  { ticker: "FLGT", sector: "Health Care" },
  { ticker: "NECB", sector: "Financials" },
  { ticker: "AGL", sector: "Health Care" },
  { ticker: "PBYI", sector: "Health Care" },
  { ticker: "ONIT", sector: "Financials" },
  { ticker: "TSBK", sector: "Financials" },
  { ticker: "ACIC", sector: "Financials" },
  { ticker: "DNA", sector: "Health Care" },
  { ticker: "HNST", sector: "Consumer Staples" },
  { ticker: "CYH", sector: "Health Care" },
  { ticker: "MAX", sector: "Communication Services" },
  { ticker: "ISTR", sector: "Financials" },
  { ticker: "CADL", sector: "Health Care" },
  { ticker: "SVV", sector: "Consumer Discretionary" },
  { ticker: "AURA", sector: "Health Care" },
  { ticker: "NMAX", sector: "Communication Services" },
  { ticker: "DCTH", sector: "Health Care" },
  { ticker: "PLBC", sector: "Financials" },
  { ticker: "SSP", sector: "Communication Services" },
  { ticker: "UPB", sector: "Health Care" },
  { ticker: "CCRN", sector: "Health Care" },
  { ticker: "DGICA", sector: "Financials" },
  { ticker: "CRSR", sector: "Information Technology" },
  { ticker: "VMD", sector: "Health Care" },
  { ticker: "TECX", sector: "Health Care" },
  { ticker: "CZFS", sector: "Financials" },
  { ticker: "FRST", sector: "Financials" },
  { ticker: "EDIT", sector: "Health Care" },
  { ticker: "RCKT", sector: "Health Care" },
  { ticker: "DDD", sector: "Industrials" },
  { ticker: "MVBF", sector: "Financials" },
  { ticker: "SPT", sector: "Information Technology" },
  { ticker: "BMBL", sector: "Communication Services" },
  { ticker: "VOXR", sector: "Materials" },
  { ticker: "HCKT", sector: "Information Technology" },
  { ticker: "HVT", sector: "Consumer Discretionary" },
  { ticker: "RCKY", sector: "Consumer Discretionary" },
  { ticker: "NWFL", sector: "Financials" },
  { ticker: "DSGN", sector: "Health Care" },
  { ticker: "FSBW", sector: "Financials" },
  { ticker: "WEAV", sector: "Information Technology" },
  { ticker: "ALIT", sector: "Industrials" },
  { ticker: "PSNL", sector: "Health Care" },
  { ticker: "XPER", sector: "Information Technology" },
  { ticker: "CLPT", sector: "Health Care" },
  { ticker: "FSTR", sector: "Industrials" },
  { ticker: "JOUT", sector: "Consumer Discretionary" },
  { ticker: "PCB", sector: "Financials" },
  { ticker: "NGNE", sector: "Health Care" },
  { ticker: "ACCO", sector: "Industrials" },
  { ticker: "GRNT", sector: "Energy" },
  { ticker: "DNUT", sector: "Consumer Discretionary" },
  { ticker: "KELYA", sector: "Industrials" },
  { ticker: "PSFE", sector: "Financials" },
  { ticker: "ATNI", sector: "Communication Services" },
  { ticker: "SWIM", sector: "Consumer Discretionary" },
  { ticker: "RPAY", sector: "Financials" },
  { ticker: "EVGO", sector: "Consumer Discretionary" },
  { ticker: "AVXL", sector: "Health Care" },
  { ticker: "GNE", sector: "Utilities" },
  { ticker: "SITC", sector: "Real Estate" },
  { ticker: "IBEX", sector: "Industrials" },
  { ticker: "EOLS", sector: "Health Care" },
  { ticker: "AMCX", sector: "Communication Services" },
  { ticker: "MEC", sector: "Industrials" },
  { ticker: "ACRE", sector: "Financials" },
  { ticker: "DBI", sector: "Consumer Discretionary" },
  { ticker: "OLPX", sector: "Consumer Staples" },
  { ticker: "MGPI", sector: "Consumer Staples" },
  { ticker: "MBI", sector: "Financials" },
  { ticker: "RLGT", sector: "Industrials" },
  { ticker: "LILA", sector: "Communication Services" },
  { ticker: "BLND", sector: "Information Technology" },
  { ticker: "WSBF", sector: "Financials" },
  { ticker: "RXST", sector: "Health Care" },
  { ticker: "CATX", sector: "Health Care" },
  { ticker: "RMR", sector: "Real Estate" },
  { ticker: "NATH", sector: "Consumer Discretionary" },
  { ticker: "KIDS", sector: "Health Care" },
  { ticker: "RC", sector: "Financials" },
  { ticker: "PKOH", sector: "Industrials" },
  { ticker: "CNDT", sector: "Industrials" },
  { ticker: "GBFH", sector: "Financials" },
  { ticker: "CDZI", sector: "Utilities" },
  { ticker: "BOC", sector: "Communication Services" },
  { ticker: "EVEX", sector: "Industrials" },
  { ticker: "ATLO", sector: "Financials" },
  { ticker: "ACH", sector: "Health Care" },
  { ticker: "DSGR", sector: "Industrials" },
  { ticker: "AVNW", sector: "Information Technology" },
  { ticker: "TARA", sector: "Health Care" },
  { ticker: "JMSB", sector: "Financials" },
  { ticker: "ELDN", sector: "Health Care" },
  { ticker: "HLLY", sector: "Consumer Discretionary" },
  { ticker: "BKTI", sector: "Information Technology" },
  { ticker: "MEI", sector: "Information Technology" },
  { ticker: "LAB", sector: "Health Care" },
  { ticker: "ABEO", sector: "Health Care" },
  { ticker: "WOOF", sector: "Consumer Discretionary" },
  { ticker: "CIA", sector: "Financials" },
  { ticker: "ANGI", sector: "Communication Services" },
  { ticker: "NAGE", sector: "Consumer Staples" },
  { ticker: "TOI", sector: "Health Care" },
  { ticker: "RBBN", sector: "Information Technology" },
  { ticker: "SMC", sector: "Energy" },
  { ticker: "EVMN", sector: "Health Care" },
  { ticker: "EGHT", sector: "Information Technology" },
  { ticker: "CHMG", sector: "Financials" },
  { ticker: "MITT", sector: "Financials" },
  { ticker: "FVCB", sector: "Financials" },
  { ticker: "ALMU", sector: "Information Technology" },
  { ticker: "INR", sector: "Energy" },
  { ticker: "HDSN", sector: "Industrials" },
  { ticker: "BETR", sector: "Financials" },
  { ticker: "JRVR", sector: "Financials" },
  { ticker: "FBYD", sector: "Industrials" },
  { ticker: "FRPH", sector: "Real Estate" },
  { ticker: "FTK", sector: "Materials" },
  { ticker: "PINE", sector: "Real Estate" },
  { ticker: "TBRG", sector: "Health Care" },
  { ticker: "OPRT", sector: "Financials" },
  { ticker: "CTRN", sector: "Consumer Discretionary" },
  { ticker: "KFS", sector: "Financials" },
  { ticker: "CMTG", sector: "Financials" },
  { ticker: "KRT", sector: "Industrials" },
  { ticker: "TG", sector: "Materials" },
  { ticker: "SLP", sector: "Health Care" },
  { ticker: "ASLE", sector: "Industrials" },
  { ticker: "MNPR", sector: "Health Care" },
  { ticker: "HYLN", sector: "Industrials" },
  { ticker: "OVLY", sector: "Financials" },
  { ticker: "NCMI", sector: "Communication Services" },
  { ticker: "FDBC", sector: "Financials" },
  { ticker: "BNTC", sector: "Health Care" },
  { ticker: "OPFI", sector: "Financials" },
  { ticker: "FRAF", sector: "Financials" },
  { ticker: "CRCT", sector: "Consumer Discretionary" },
  { ticker: "STRZ", sector: "Communication Services" },
  { ticker: "QUAD", sector: "Industrials" },
  { ticker: "ARCT", sector: "Health Care" },
  { ticker: "NKSH", sector: "Financials" },
  { ticker: "CDXS", sector: "Health Care" },
  { ticker: "NEXN", sector: "Communication Services" },
  { ticker: "RZLT", sector: "Health Care" },
  { ticker: "ALCO", sector: "Consumer Staples" },
  { ticker: "AII", sector: "Financials" },
  { ticker: "TLS", sector: "Information Technology" },
  { ticker: "LOVE", sector: "Consumer Discretionary" },
  { ticker: "ASPN", sector: "Materials" },
  { ticker: "ARDT", sector: "Health Care" },
  { ticker: "CMT", sector: "Materials" },
  { ticker: "WNEB", sector: "Financials" },
  { ticker: "ULCC", sector: "Industrials" },
  { ticker: "EVC", sector: "Communication Services" },
  { ticker: "VEL", sector: "Financials" },
  { ticker: "BRBS", sector: "Financials" },
  { ticker: "PAYS", sector: "Financials" },
  { ticker: "MYFW", sector: "Financials" },
  { ticker: "XRX", sector: "Information Technology" },
  { ticker: "CLW", sector: "Materials" },
  { ticker: "BLZE", sector: "Information Technology" },
  { ticker: "OSUR", sector: "Health Care" },
  { ticker: "PCYO", sector: "Utilities" },
  { ticker: "FUNC", sector: "Financials" },
  { ticker: "REFI", sector: "Financials" },
  { ticker: "PESI", sector: "Industrials" },
  { ticker: "USNA", sector: "Consumer Staples" },
  { ticker: "VTEX", sector: "Information Technology" },
  { ticker: "ACDC", sector: "Energy" },
  { ticker: "FC", sector: "Industrials" },
  { ticker: "JACK", sector: "Consumer Discretionary" },
  { ticker: "LRMR", sector: "Health Care" },
  { ticker: "ALEC", sector: "Health Care" },
  { ticker: "WBTN", sector: "Communication Services" },
  { ticker: "PANL", sector: "Industrials" },
  { ticker: "ASUR", sector: "Industrials" },
  { ticker: "LMRI", sector: "Health Care" },
  { ticker: "MG", sector: "Industrials" },
  { ticker: "BSVN", sector: "Financials" },
  { ticker: "FBLA", sector: "Financials" },
  { ticker: "CRDA", sector: "Financials" },
  { ticker: "BRCB", sector: "Consumer Discretionary" },
  { ticker: "LCNB", sector: "Financials" },
  { ticker: "CMRC", sector: "Information Technology" },
  { ticker: "CFFI", sector: "Financials" },
  { ticker: "DMAC", sector: "Health Care" },
  { ticker: "SPOK", sector: "Communication Services" },
  { ticker: "NLOP", sector: "Real Estate" },
  { ticker: "KINS", sector: "Financials" },
  { ticker: "NRC", sector: "Health Care" },
  { ticker: "USAU", sector: "Materials" },
  { ticker: "JAKK", sector: "Consumer Discretionary" },
  { ticker: "USCB", sector: "Financials" },
  { ticker: "SKYH", sector: "Industrials" },
  { ticker: "LMNR", sector: "Consumer Staples" },
  { ticker: "RICK", sector: "Consumer Discretionary" },
  { ticker: "BH", sector: "Consumer Discretionary" },
  { ticker: "REPL", sector: "Health Care" },
  { ticker: "VABK", sector: "Financials" },
  { ticker: "POWW", sector: "Consumer Discretionary" },
  { ticker: "RSVR", sector: "Communication Services" },
  { ticker: "BPRN", sector: "Financials" },
  { ticker: "NXDT", sector: "Real Estate" },
  { ticker: "STRS", sector: "Real Estate" },
  { ticker: "VYGR", sector: "Health Care" },
  { ticker: "CD", sector: "Information Technology" },
  { ticker: "MASS", sector: "Information Technology" },
  { ticker: "TBCH", sector: "Information Technology" },
  { ticker: "ESOA", sector: "Energy" },
  { ticker: "INSG", sector: "Information Technology" },
  { ticker: "ANIK", sector: "Health Care" },
  { ticker: "MPTI", sector: "Information Technology" },
  { ticker: "IKT", sector: "Health Care" },
  { ticker: "WYFI", sector: "Information Technology" },
  { ticker: "MVIS", sector: "Information Technology" },
  { ticker: "WEST", sector: "Consumer Staples" },
  { ticker: "PDYN", sector: "Industrials" },
  { ticker: "SEVN", sector: "Financials" },
  { ticker: "WEYS", sector: "Consumer Discretionary" },
  { ticker: "ATOM", sector: "Information Technology" },
  { ticker: "PEBK", sector: "Financials" },
  { ticker: "CTEV", sector: "Health Care" },
  { ticker: "PLTK", sector: "Communication Services" },
  { ticker: "SNDA", sector: "Health Care" },
  { ticker: "MRBK", sector: "Financials" },
  { ticker: "PACK", sector: "Materials" },
  { ticker: "SIGA", sector: "Health Care" },
  { ticker: "XPOF", sector: "Consumer Discretionary" },
  { ticker: "UIS", sector: "Information Technology" },
  { ticker: "ZIP", sector: "Communication Services" },
  { ticker: "OSG", sector: "Financials" },
  { ticker: "FCCO", sector: "Financials" },
  { ticker: "SGHT", sector: "Health Care" },
  { ticker: "LFMD", sector: "Health Care" },
  { ticker: "LENZ", sector: "Health Care" },
  { ticker: "CHRS", sector: "Health Care" },
  { ticker: "RMNI", sector: "Information Technology" },
  { ticker: "BNED", sector: "Consumer Discretionary" },
  { ticker: "BZAI", sector: "Information Technology" },
  { ticker: "MFIN", sector: "Financials" },
  { ticker: "NC", sector: "Energy" },
  { ticker: "INBK", sector: "Financials" },
  { ticker: "KGEI", sector: "Energy" },
  { ticker: "LPRO", sector: "Financials" },
  { ticker: "IMMR", sector: "Information Technology" },
  { ticker: "FXNC", sector: "Financials" },
  { ticker: "ESCA", sector: "Consumer Discretionary" },
  { ticker: "FNKO", sector: "Consumer Discretionary" },
  { ticker: "ASIC", sector: "Financials" },
  { ticker: "BBCP", sector: "Industrials" },
  { ticker: "COSO", sector: "Financials" },
  { ticker: "INSE", sector: "Consumer Discretionary" },
  { ticker: "CBK", sector: "Financials" },
  { ticker: "FLXS", sector: "Consumer Discretionary" },
  { ticker: "RELL", sector: "Information Technology" },
  { ticker: "GCBC", sector: "Financials" },
  { ticker: "FENC", sector: "Health Care" },
  { ticker: "RNA", sector: "Health Care" },
  { ticker: "TNXP", sector: "Health Care" },
  { ticker: "KRMD", sector: "Health Care" },
  { ticker: "FHTX", sector: "Health Care" },
  { ticker: "EWCZ", sector: "Consumer Discretionary" },
  { ticker: "UTMD", sector: "Health Care" },
  { ticker: "VUZI", sector: "Information Technology" },
  { ticker: "INGN", sector: "Health Care" },
  { ticker: "LNKB", sector: "Financials" },
  { ticker: "ACTG", sector: "Financials" },
  { ticker: "ELMD", sector: "Health Care" },
  { ticker: "OPBK", sector: "Financials" },
  { ticker: "RGCO", sector: "Utilities" },
  { ticker: "EVCM", sector: "Information Technology" },
  { ticker: "CZWI", sector: "Financials" },
  { ticker: "OVBC", sector: "Financials" },
  { ticker: "AIRO", sector: "Industrials" },
  { ticker: "ULH", sector: "Industrials" },
  { ticker: "ORGO", sector: "Health Care" },
  { ticker: "VIA", sector: "Information Technology" },
  { ticker: "BRT", sector: "Real Estate" },
  { ticker: "QSI", sector: "Health Care" },
  { ticker: "LEGH", sector: "Consumer Discretionary" },
  { ticker: "PBFS", sector: "Financials" },
  { ticker: "III", sector: "Information Technology" },
  { ticker: "OABI", sector: "Health Care" },
  { ticker: "PAL", sector: "Industrials" },
  { ticker: "BCBP", sector: "Financials" },
  { ticker: "FCAP", sector: "Financials" },
  { ticker: "HRTX", sector: "Health Care" },
  { ticker: "LDI", sector: "Financials" },
  { ticker: "SEG", sector: "Real Estate" },
  { ticker: "ALTI", sector: "Financials" },
  { ticker: "HWBK", sector: "Financials" },
  { ticker: "RXT", sector: "Information Technology" },
  { ticker: "GLSI", sector: "Health Care" },
  { ticker: "DSP", sector: "Information Technology" },
  { ticker: "HBB", sector: "Consumer Discretionary" },
  { ticker: "PRTH", sector: "Financials" },
  { ticker: "KRO", sector: "Materials" },
  { ticker: "MPAA", sector: "Consumer Discretionary" },
  { ticker: "SMHI", sector: "Energy" },
  { ticker: "INNV", sector: "Health Care" },
  { ticker: "TTGT", sector: "Communication Services" },
  { ticker: "CURI", sector: "Communication Services" },
  { ticker: "PLX", sector: "Health Care" },
  { ticker: "BKKT", sector: "Financials" },
  { ticker: "ALTG", sector: "Industrials" },
  { ticker: "HPK", sector: "Energy" },
  { ticker: "SNFCA", sector: "Financials" },
  { ticker: "MDWD", sector: "Health Care" },
  { ticker: "EFSI", sector: "Financials" },
  { ticker: "CMDB", sector: "Industrials" },
  { ticker: "FATE", sector: "Health Care" },
  { ticker: "MNSB", sector: "Financials" },
  { ticker: "DOUG", sector: "Real Estate" },
  { ticker: "BVFL", sector: "Financials" },
  { ticker: "TBI", sector: "Industrials" },
  { ticker: "CV", sector: "Health Care" },
  { ticker: "BHR", sector: "Real Estate" },
  { ticker: "SNWV", sector: "Health Care" },
  { ticker: "RCMT", sector: "Industrials" },
  { ticker: "LWAY", sector: "Consumer Staples" },
  { ticker: "PMTS", sector: "Information Technology" },
  { ticker: "LZM", sector: "Materials" },
  { ticker: "NKTX", sector: "Health Care" },
  { ticker: "GENC", sector: "Industrials" },
  { ticker: "LFCR", sector: "Health Care" },
  { ticker: "QTRX", sector: "Health Care" },
  { ticker: "EBMT", sector: "Financials" },
  { ticker: "SAMG", sector: "Financials" },
  { ticker: "EPM", sector: "Energy" },
  { ticker: "CFBK", sector: "Financials" },
  { ticker: "FINW", sector: "Financials" },
  { ticker: "DOMO", sector: "Information Technology" },
  { ticker: "MDV", sector: "Real Estate" },
  { ticker: "NREF", sector: "Financials" },
  { ticker: "NVCT", sector: "Health Care" },
  { ticker: "CBFV", sector: "Financials" },
  { ticker: "SGC", sector: "Consumer Discretionary" },
  { ticker: "RGP", sector: "Industrials" },
  { ticker: "ADV", sector: "Communication Services" },
  { ticker: "RMAX", sector: "Real Estate" },
  { ticker: "MED", sector: "Consumer Staples" },
  { ticker: "ACU", sector: "Health Care" },
  { ticker: "EVI", sector: "Industrials" },
  { ticker: "PXED", sector: "Consumer Discretionary" },
  { ticker: "TLSI", sector: "Health Care" },
  { ticker: "CVRX", sector: "Health Care" },
  { ticker: "ACR", sector: "Financials" },
  { ticker: "EGAN", sector: "Information Technology" },
  { ticker: "SI", sector: "Health Care" },
  { ticker: "SLQT", sector: "Financials" },
  { ticker: "NNOX", sector: "Health Care" },
  { ticker: "FRD", sector: "Materials" },
  { ticker: "PDEX", sector: "Health Care" },
  { ticker: "ONEW", sector: "Consumer Discretionary" },
  { ticker: "SRBK", sector: "Financials" },
  { ticker: "STXS", sector: "Health Care" },
  { ticker: "JELD", sector: "Industrials" },
  { ticker: "AOMR", sector: "Financials" },
  { ticker: "PNRG", sector: "Energy" },
  { ticker: "FOA", sector: "Financials" },
  { ticker: "EML", sector: "Industrials" },
  { ticker: "BYRN", sector: "Industrials" },
  { ticker: "DMRC", sector: "Information Technology" },
  { ticker: "NFE", sector: "Energy" },
  { ticker: "HUMA", sector: "Health Care" },
  { ticker: "BOOM", sector: "Energy" },
  { ticker: "MLP", sector: "Real Estate" },
  { ticker: "KLC", sector: "Consumer Discretionary" },
  { ticker: "TCX", sector: "Information Technology" },
  { ticker: "THRY", sector: "Communication Services" },
  { ticker: "LE", sector: "Consumer Discretionary" },
  { ticker: "BSET", sector: "Consumer Discretionary" },
  { ticker: "CXDO", sector: "Information Technology" },
  { ticker: "BALY", sector: "Consumer Discretionary" },
  { ticker: "KULR", sector: "Industrials" },
  { ticker: "FF", sector: "Energy" },
  { ticker: "CRDF", sector: "Health Care" },
  { ticker: "EPSN", sector: "Energy" },
  { ticker: "OPRX", sector: "Health Care" },
  { ticker: "NODK", sector: "Financials" },
  { ticker: "OFLX", sector: "Industrials" },
  { ticker: "LAW", sector: "Information Technology" },
  { ticker: "KLTR", sector: "Information Technology" },
  { ticker: "AOUT", sector: "Consumer Discretionary" },
  { ticker: "SBFG", sector: "Financials" },
  { ticker: "SMID", sector: "Materials" },
  { ticker: "ACNT", sector: "Materials" },
  { ticker: "LARK", sector: "Financials" },
  { ticker: "ELA", sector: "Consumer Discretionary" },
  { ticker: "LUCD", sector: "Health Care" },
  { ticker: "BRCC", sector: "Consumer Staples" },
  { ticker: "JILL", sector: "Consumer Discretionary" },
  { ticker: "JYNT", sector: "Health Care" },
  { ticker: "SKIN", sector: "Consumer Staples" },
  { ticker: "STRW", sector: "Real Estate" },
  { ticker: "AIRJ", sector: "Industrials" },
  { ticker: "CRMT", sector: "Consumer Discretionary" },
  { ticker: "HCAT", sector: "Health Care" },
  { ticker: "MNTK", sector: "Utilities" },
  { ticker: "HURA", sector: "Health Care" },
  { ticker: "ALDX", sector: "Health Care" },
  { ticker: "MXCT", sector: "Health Care" },
  { ticker: "DERM", sector: "Health Care" },
  { ticker: "PNBK", sector: "Financials" },
  { ticker: "KRRO", sector: "Health Care" },
  { ticker: "TMCI", sector: "Health Care" },
  { ticker: "SKYX", sector: "Industrials" },
  { ticker: "FNWD", sector: "Financials" },
  { ticker: "FLWS", sector: "Consumer Discretionary" },
  { ticker: "GYRE", sector: "Health Care" },
  { ticker: "WHG", sector: "Financials" },
  { ticker: "TRAK", sector: "Information Technology" },
  { ticker: "RMBI", sector: "Financials" },
  { ticker: "HNVR", sector: "Financials" },
  { ticker: "XZO", sector: "Financials" },
  { ticker: "RVSB", sector: "Financials" },
  { ticker: "GWRS", sector: "Utilities" },
  { ticker: "GETY", sector: "Communication Services" },
  { ticker: "SUNS", sector: "Financials" },
  { ticker: "HAIN", sector: "Consumer Staples" },
  { ticker: "LAKE", sector: "Consumer Discretionary" },
  { ticker: "ECBK", sector: "Financials" },
  { ticker: "OM", sector: "Health Care" },
  { ticker: "CPSS", sector: "Financials" },
  { ticker: "HFFG", sector: "Consumer Staples" },
  { ticker: "ARQ", sector: "Materials" },
  { ticker: "RPT", sector: "Financials" },
  { ticker: "CLAR", sector: "Consumer Discretionary" },
  { ticker: "GAMB", sector: "Communication Services" },
  { ticker: "GOSS", sector: "Health Care" },
  { ticker: "EEX", sector: "Communication Services" },
  { ticker: "SPWR", sector: "Industrials" },
  { ticker: "SVCO", sector: "Information Technology" },
  { ticker: "FORR", sector: "Industrials" },
  { ticker: "CARL", sector: "Health Care" },
  { ticker: "AVD", sector: "Materials" },
  { ticker: "RNAC", sector: "Health Care" },
  { ticker: "ATYR", sector: "Health Care" },
  { ticker: "CBNA", sector: "Financials" },
  { ticker: "FFAI", sector: "Consumer Discretionary" },
  { ticker: "ZVIA", sector: "Consumer Staples" },
  { ticker: "AARD", sector: "Health Care" },
  { ticker: "VIRC", sector: "Industrials" },
  { ticker: "TTEC", sector: "Industrials" },
  { ticker: "STIM", sector: "Health Care" },
  { ticker: "DCGO", sector: "Health Care" },
  { ticker: "CSPI", sector: "Information Technology" },
  { ticker: "AISP", sector: "Information Technology" },
  { ticker: "BTMD", sector: "Health Care" },
  { ticker: "NPWR", sector: "Industrials" },
  { ticker: "SSTI", sector: "Information Technology" },
  { ticker: "SMTI", sector: "Health Care" },
  { ticker: "CURV", sector: "Consumer Discretionary" },
  { ticker: "UNB", sector: "Financials" },
  { ticker: "MPX", sector: "Consumer Discretionary" },
  { ticker: "RCEL", sector: "Health Care" },
  { ticker: "SFBC", sector: "Financials" },
  { ticker: "FSP", sector: "Real Estate" },
  { ticker: "NRDY", sector: "Consumer Discretionary" },
  { ticker: "INH", sector: "Health Care" },
  { ticker: "AEYE", sector: "Information Technology" },
  { ticker: "TUSK", sector: "Energy" },
  { ticker: "PAMT", sector: "Industrials" },
  { ticker: "TZOO", sector: "Communication Services" },
  { ticker: "EXFY", sector: "Information Technology" },
  { ticker: "LFVN", sector: "Consumer Staples" },
  { ticker: "TCI", sector: "Real Estate" },
  { ticker: "LNSR", sector: "Health Care" },
  { ticker: "AKE", sector: "Health Care" },
  { ticker: "AVBH", sector: "Financials" },
  { ticker: "EHTH", sector: "Financials" },
  { ticker: "PPHC", sector: "Industrials" },
  { ticker: "OPAL", sector: "Energy" },
  { ticker: "LUNG", sector: "Health Care" },
  { ticker: "BARK", sector: "Consumer Discretionary" },
  { ticker: "NL", sector: "Industrials" },
  { ticker: "ARAY", sector: "Health Care" },
  { ticker: "LFT", sector: "Financials" },
  { ticker: "SNBR", sector: "Consumer Discretionary" },
  { ticker: "HQI", sector: "Industrials" },
  { ticker: "RBKB", sector: "Financials" },
  { ticker: "CLPR", sector: "Real Estate" },
  { ticker: "LVWR", sector: "Consumer Discretionary" },
  { ticker: "GAIA", sector: "Communication Services" },
  { ticker: "VHI", sector: "Materials" },
  { ticker: "EP", sector: "Energy" },
  { ticker: "MYPS", sector: "Communication Services" },
  { ticker: "PROP", sector: "Energy" },
  { ticker: "MKTW", sector: "Financials" },
  { ticker: "AIRS", sector: "Health Care" },
  { ticker: "USGO", sector: "Materials" },
  { ticker: "SEAT", sector: "Communication Services" },
  { ticker: "SKIL", sector: "Industrials" },
  { ticker: "DH", sector: "Health Care" },
  { ticker: "TKNO", sector: "Health Care" },
  { ticker: "WALD", sector: "Consumer Staples" },
  { ticker: "VALU", sector: "Financials" },
  { ticker: "SBC", sector: "Health Care" },
  { ticker: "TEAD", sector: "Communication Services" },
  { ticker: "CIX", sector: "Industrials" },
  { ticker: "ISPR", sector: "Consumer Staples" },
  { ticker: "FTLF", sector: "Consumer Staples" },
  { ticker: "KG", sector: "Financials" },
  { ticker: "AREN", sector: "Communication Services" },
  { ticker: "MYO", sector: "Health Care" },
  { ticker: "COOK", sector: "Consumer Discretionary" },
  { ticker: "INMB", sector: "Health Care" },
  { ticker: "SIEB", sector: "Financials" },
  { ticker: "TVRD", sector: "Health Care" },
  { ticker: "AFRI", sector: "Consumer Staples" },
  { ticker: "ACTU", sector: "Health Care" },
  { ticker: "ARL", sector: "Real Estate" },
  { ticker: "NEON", sector: "Information Technology" },
  { ticker: "BEEP", sector: "Industrials" },
  { ticker: "SLSN", sector: "Materials" },
  { ticker: "VRM", sector: "Financials" },
  { ticker: "ATLN", sector: "Health Care" },
  { ticker: "NXXT", sector: "Energy" },
  { ticker: "ADRO", sector: "Health Care" },
  { ticker: "MRDN", sector: "Communication Services" },
  { ticker: "SLND", sector: "Industrials" },
  { ticker: "SAFX", sector: "Energy" },
  { ticker: "GOCO", sector: "Financials" },
  { ticker: "VGAS", sector: "Energy" },
  { ticker: "ADRO", sector: "Health Care" },
  { ticker: "TSEOF", sector: "Materials" },
  { ticker: "TVGN", sector: "Health Care" },
  { ticker: "PDLI", sector: "Health Care" },
  { ticker: "GTXI", sector: "Health Care" },
  { ticker: "P5N994", sector: "Energy" },
  { ticker: "SBT", sector: "Financials" },
  { ticker: "THRD", sector: "Health Care" },
  { ticker: "ZSPC", sector: "Consumer Discretionary" },
];
