import type { ScreenableCompany } from "@/lib/screener/cac40";

// Full S&P MidCap 400 constituent list sourced from Wikipedia (April 2025).
// Index membership changes quarterly; acquired or delisted tickers will appear
// as error rows in the screener and can be ignored.
export const SP400_COMPANIES: ScreenableCompany[] = [
  { ticker: "AA", sector: "Materials" },
  { ticker: "AAL", sector: "Industrials" },
  { ticker: "AAON", sector: "Industrials" },
  { ticker: "ACI", sector: "Consumer Staples" },
  { ticker: "ACM", sector: "Industrials" },
  { ticker: "ADC", sector: "Real Estate" },
  { ticker: "AEIS", sector: "Information Technology" },
  { ticker: "AFG", sector: "Financials" },
  { ticker: "AGCO", sector: "Industrials" },
  { ticker: "AHR", sector: "Real Estate" },
  { ticker: "AIT", sector: "Industrials" },
  { ticker: "ALGM", sector: "Information Technology" },
  { ticker: "ALK", sector: "Industrials" },
  { ticker: "ALLY", sector: "Financials" },
  { ticker: "ALV", sector: "Consumer Discretionary" },
  { ticker: "AM", sector: "Energy" },
  { ticker: "AMG", sector: "Financials" },
  { ticker: "AMH", sector: "Real Estate" },
  { ticker: "AMKR", sector: "Information Technology" },
  { ticker: "AN", sector: "Consumer Discretionary" },
  { ticker: "ANF", sector: "Consumer Discretionary" },
  { ticker: "APG", sector: "Industrials" },
  { ticker: "APPF", sector: "Information Technology" },
  { ticker: "AR", sector: "Energy" },
  { ticker: "ARMK", sector: "Consumer Discretionary" },
  { ticker: "ARW", sector: "Information Technology" },
  { ticker: "ARWR", sector: "Health Care" },
  { ticker: "ASB", sector: "Financials" },
  { ticker: "ASH", sector: "Materials" },
  { ticker: "ATI", sector: "Industrials" },
  { ticker: "ATR", sector: "Materials" },
  { ticker: "AVAV", sector: "Industrials" },
  { ticker: "AVNT", sector: "Materials" },
  { ticker: "AVT", sector: "Information Technology" },
  { ticker: "AVTR", sector: "Health Care" },
  { ticker: "AXTA", sector: "Materials" },
  { ticker: "AYI", sector: "Industrials" },
  { ticker: "BAH", sector: "Industrials" },
  { ticker: "BBWI", sector: "Consumer Discretionary" },
  { ticker: "BC", sector: "Consumer Discretionary" },
  { ticker: "BCO", sector: "Industrials" },
  { ticker: "BDC", sector: "Information Technology" },
  { ticker: "BHF", sector: "Financials" },
  { ticker: "BILL", sector: "Information Technology" },
  { ticker: "BIO", sector: "Health Care" },
  { ticker: "BJ", sector: "Consumer Staples" },
  { ticker: "BKH", sector: "Utilities" },
  { ticker: "BLD", sector: "Consumer Discretionary" },
  { ticker: "BLKB", sector: "Information Technology" },
  { ticker: "BMRN", sector: "Health Care" },
  { ticker: "BRBR", sector: "Consumer Staples" },
  { ticker: "BRKR", sector: "Health Care" },
  { ticker: "BROS", sector: "Consumer Discretionary" },
  { ticker: "BRX", sector: "Real Estate" },
  { ticker: "BSY", sector: "Information Technology" },
  { ticker: "BURL", sector: "Consumer Discretionary" },
  { ticker: "BWA", sector: "Consumer Discretionary" },
  { ticker: "BWXT", sector: "Industrials" },
  { ticker: "BYD", sector: "Consumer Discretionary" },
  { ticker: "CACI", sector: "Industrials" },
  { ticker: "CAR", sector: "Industrials" },
  { ticker: "CART", sector: "Consumer Staples" },
  { ticker: "CAVA", sector: "Consumer Discretionary" },
  { ticker: "CBSH", sector: "Financials" },
  { ticker: "CBT", sector: "Materials" },
  { ticker: "CCK", sector: "Materials" },
  { ticker: "CDP", sector: "Real Estate" },
  { ticker: "CELH", sector: "Consumer Staples" },
  { ticker: "CFR", sector: "Financials" },
  { ticker: "CG", sector: "Financials" },
  { ticker: "CGNX", sector: "Information Technology" },
  { ticker: "CHDN", sector: "Consumer Discretionary" },
  { ticker: "CHE", sector: "Health Care" },
  { ticker: "CHH", sector: "Consumer Discretionary" },
  { ticker: "CHRD", sector: "Energy" },
  { ticker: "CHWY", sector: "Consumer Discretionary" },
  { ticker: "CLF", sector: "Materials" },
  { ticker: "CLH", sector: "Industrials" },
  { ticker: "CMC", sector: "Materials" },
  { ticker: "CNH", sector: "Industrials" },
  { ticker: "CNM", sector: "Industrials" },
  { ticker: "CNO", sector: "Financials" },
  { ticker: "CNX", sector: "Energy" },
  { ticker: "CNXC", sector: "Industrials" },
  { ticker: "COKE", sector: "Consumer Staples" },
  { ticker: "COLB", sector: "Financials" },
  { ticker: "COLM", sector: "Consumer Discretionary" },
  { ticker: "COTY", sector: "Consumer Staples" },
  { ticker: "CPRI", sector: "Consumer Discretionary" },
  { ticker: "CR", sector: "Industrials" },
  { ticker: "CRBG", sector: "Financials" },
  { ticker: "CROX", sector: "Consumer Discretionary" },
  { ticker: "CRS", sector: "Industrials" },
  { ticker: "CRUS", sector: "Information Technology" },
  { ticker: "CSL", sector: "Industrials" },
  { ticker: "CTRE", sector: "Real Estate" },
  { ticker: "CUBE", sector: "Real Estate" },
  { ticker: "CUZ", sector: "Real Estate" },
  { ticker: "CVLT", sector: "Information Technology" },
  { ticker: "CW", sector: "Industrials" },
  { ticker: "CXT", sector: "Information Technology" },
  { ticker: "CYTK", sector: "Health Care" },
  { ticker: "DAR", sector: "Consumer Staples" },
  { ticker: "DBX", sector: "Information Technology" },
  { ticker: "DCI", sector: "Industrials" },
  { ticker: "DINO", sector: "Energy" },
  { ticker: "DKS", sector: "Consumer Discretionary" },
  { ticker: "DLB", sector: "Information Technology" },
  { ticker: "DOCN", sector: "Information Technology" },
  { ticker: "DOCS", sector: "Health Care" },
  { ticker: "DOCU", sector: "Information Technology" },
  { ticker: "DT", sector: "Information Technology" },
  { ticker: "DTM", sector: "Energy" },
  { ticker: "DUOL", sector: "Consumer Discretionary" },
  { ticker: "DY", sector: "Industrials" },
  { ticker: "EEFT", sector: "Financials" },
  { ticker: "EGP", sector: "Real Estate" },
  { ticker: "EHC", sector: "Health Care" },
  { ticker: "ELAN", sector: "Health Care" },
  { ticker: "ELF", sector: "Consumer Staples" },
  { ticker: "ELS", sector: "Real Estate" },
  { ticker: "ENS", sector: "Industrials" },
  { ticker: "ENSG", sector: "Health Care" },
  { ticker: "ENTG", sector: "Information Technology" },
  { ticker: "EPR", sector: "Real Estate" },
  { ticker: "EQH", sector: "Financials" },
  { ticker: "ESAB", sector: "Industrials" },
  { ticker: "ESNT", sector: "Financials" },
  { ticker: "EVR", sector: "Financials" },
  { ticker: "EWBC", sector: "Financials" },
  { ticker: "EXEL", sector: "Health Care" },
  { ticker: "EXLS", sector: "Industrials" },
  { ticker: "EXP", sector: "Materials" },
  { ticker: "EXPO", sector: "Industrials" },
  { ticker: "FAF", sector: "Financials" },
  { ticker: "FBIN", sector: "Industrials" },
  { ticker: "FCFS", sector: "Financials" },
  { ticker: "FCN", sector: "Industrials" },
  { ticker: "FFIN", sector: "Financials" },
  { ticker: "FHI", sector: "Financials" },
  { ticker: "FHN", sector: "Financials" },
  { ticker: "FIVE", sector: "Consumer Discretionary" },
  { ticker: "FLEX", sector: "Information Technology" },
  { ticker: "FLG", sector: "Financials" },
  { ticker: "FLO", sector: "Consumer Staples" },
  { ticker: "FLR", sector: "Industrials" },
  { ticker: "FLS", sector: "Industrials" },
  { ticker: "FN", sector: "Information Technology" },
  { ticker: "FNB", sector: "Financials" },
  { ticker: "FND", sector: "Consumer Discretionary" },
  { ticker: "FNF", sector: "Financials" },
  { ticker: "FOUR", sector: "Financials" },
  { ticker: "FR", sector: "Real Estate" },
  { ticker: "FTI", sector: "Energy" },
  { ticker: "G", sector: "Industrials" },
  { ticker: "GAP", sector: "Consumer Discretionary" },
  { ticker: "GATX", sector: "Industrials" },
  { ticker: "GBCI", sector: "Financials" },
  { ticker: "GEF", sector: "Materials" },
  { ticker: "GGG", sector: "Industrials" },
  { ticker: "GHC", sector: "Consumer Discretionary" },
  { ticker: "GLPI", sector: "Real Estate" },
  { ticker: "GME", sector: "Consumer Discretionary" },
  { ticker: "GMED", sector: "Health Care" },
  { ticker: "GNTX", sector: "Consumer Discretionary" },
  { ticker: "GPK", sector: "Materials" },
  { ticker: "GT", sector: "Consumer Discretionary" },
  { ticker: "GTLS", sector: "Industrials" },
  { ticker: "GWRE", sector: "Information Technology" },
  { ticker: "GXO", sector: "Industrials" },
  { ticker: "H", sector: "Consumer Discretionary" },
  { ticker: "HAE", sector: "Health Care" },
  { ticker: "HALO", sector: "Health Care" },
  { ticker: "HGV", sector: "Consumer Discretionary" },
  { ticker: "HIMS", sector: "Health Care" },
  { ticker: "HL", sector: "Materials" },
  { ticker: "HLI", sector: "Financials" },
  { ticker: "HLNE", sector: "Financials" },
  { ticker: "HOG", sector: "Consumer Discretionary" },
  { ticker: "HOMB", sector: "Financials" },
  { ticker: "HQY", sector: "Health Care" },
  { ticker: "HR", sector: "Real Estate" },
  { ticker: "HRB", sector: "Consumer Discretionary" },
  { ticker: "HWC", sector: "Financials" },
  { ticker: "HXL", sector: "Industrials" },
  { ticker: "IBOC", sector: "Financials" },
  { ticker: "IDA", sector: "Utilities" },
  { ticker: "IDCC", sector: "Information Technology" },
  { ticker: "ILMN", sector: "Health Care" },
  { ticker: "INGR", sector: "Consumer Staples" },
  { ticker: "IPGP", sector: "Information Technology" },
  { ticker: "IRT", sector: "Real Estate" },
  { ticker: "ITT", sector: "Industrials" },
  { ticker: "JAZZ", sector: "Health Care" },
  { ticker: "JEF", sector: "Financials" },
  { ticker: "JHG", sector: "Financials" },
  { ticker: "JLL", sector: "Real Estate" },
  { ticker: "KBH", sector: "Consumer Discretionary" },
  { ticker: "KBR", sector: "Industrials" },
  { ticker: "KD", sector: "Information Technology" },
  { ticker: "KEX", sector: "Industrials" },
  { ticker: "KNF", sector: "Materials" },
  { ticker: "KNSL", sector: "Financials" },
  { ticker: "KNX", sector: "Industrials" },
  { ticker: "KRC", sector: "Real Estate" },
  { ticker: "KRG", sector: "Real Estate" },
  { ticker: "KTOS", sector: "Industrials" },
  { ticker: "LAD", sector: "Consumer Discretionary" },
  { ticker: "LAMR", sector: "Real Estate" },
  { ticker: "LEA", sector: "Consumer Discretionary" },
  { ticker: "LECO", sector: "Industrials" },
  { ticker: "LFUS", sector: "Information Technology" },
  { ticker: "LIVN", sector: "Health Care" },
  { ticker: "LNTH", sector: "Health Care" },
  { ticker: "LOPE", sector: "Consumer Discretionary" },
  { ticker: "LPX", sector: "Materials" },
  { ticker: "LSCC", sector: "Information Technology" },
  { ticker: "LSTR", sector: "Industrials" },
  { ticker: "M", sector: "Consumer Discretionary" },
  { ticker: "MANH", sector: "Information Technology" },
  { ticker: "MASI", sector: "Health Care" },
  { ticker: "MAT", sector: "Consumer Discretionary" },
  { ticker: "MEDP", sector: "Health Care" },
  { ticker: "MIDD", sector: "Industrials" },
  { ticker: "MKSI", sector: "Information Technology" },
  { ticker: "MLI", sector: "Industrials" },
  { ticker: "MMS", sector: "Industrials" },
  { ticker: "MOG-A", sector: "Industrials" },
  { ticker: "MORN", sector: "Financials" },
  { ticker: "MP", sector: "Materials" },
  { ticker: "MSA", sector: "Industrials" },
  { ticker: "MSM", sector: "Industrials" },
  { ticker: "MTDR", sector: "Energy" },
  { ticker: "MTG", sector: "Financials" },
  { ticker: "MTN", sector: "Consumer Discretionary" },
  { ticker: "MTSI", sector: "Information Technology" },
  { ticker: "MTZ", sector: "Industrials" },
  { ticker: "MUR", sector: "Energy" },
  { ticker: "MUSA", sector: "Consumer Discretionary" },
  { ticker: "NBIX", sector: "Health Care" },
  { ticker: "NEU", sector: "Materials" },
  { ticker: "NFG", sector: "Utilities" },
  { ticker: "NJR", sector: "Utilities" },
  { ticker: "NLY", sector: "Financials" },
  { ticker: "NNN", sector: "Real Estate" },
  { ticker: "NOV", sector: "Energy" },
  { ticker: "NOVT", sector: "Information Technology" },
  { ticker: "NSA", sector: "Real Estate" },
  { ticker: "NTNX", sector: "Information Technology" },
  { ticker: "NVST", sector: "Health Care" },
  { ticker: "NVT", sector: "Industrials" },
  { ticker: "NWE", sector: "Utilities" },
  { ticker: "NXST", sector: "Communication Services" },
  { ticker: "NXT", sector: "Industrials" },
  { ticker: "NYT", sector: "Communication Services" },
  { ticker: "OC", sector: "Industrials" },
  { ticker: "OGE", sector: "Utilities" },
  { ticker: "OGS", sector: "Utilities" },
  { ticker: "OHI", sector: "Real Estate" },
  { ticker: "OKTA", sector: "Information Technology" },
  { ticker: "OLED", sector: "Information Technology" },
  { ticker: "OLLI", sector: "Consumer Discretionary" },
  { ticker: "OLN", sector: "Materials" },
  { ticker: "ONB", sector: "Financials" },
  { ticker: "ONTO", sector: "Information Technology" },
  { ticker: "OPCH", sector: "Health Care" },
  { ticker: "ORA", sector: "Utilities" },
  { ticker: "ORI", sector: "Financials" },
  { ticker: "OSK", sector: "Industrials" },
  { ticker: "OVV", sector: "Energy" },
  { ticker: "OZK", sector: "Financials" },
  { ticker: "PAG", sector: "Consumer Discretionary" },
  { ticker: "PATH", sector: "Information Technology" },
  { ticker: "PB", sector: "Financials" },
  { ticker: "PBF", sector: "Energy" },
  { ticker: "PCTY", sector: "Industrials" },
  { ticker: "PEGA", sector: "Information Technology" },
  { ticker: "PEN", sector: "Health Care" },
  { ticker: "PFGC", sector: "Consumer Staples" },
  { ticker: "PII", sector: "Consumer Discretionary" },
  { ticker: "PINS", sector: "Communication Services" },
  { ticker: "PK", sector: "Real Estate" },
  { ticker: "PLNT", sector: "Consumer Discretionary" },
  { ticker: "PNFP", sector: "Financials" },
  { ticker: "POR", sector: "Utilities" },
  { ticker: "POST", sector: "Consumer Staples" },
  { ticker: "PPC", sector: "Consumer Staples" },
  { ticker: "PR", sector: "Energy" },
  { ticker: "PRI", sector: "Financials" },
  { ticker: "PSN", sector: "Industrials" },
  { ticker: "PSTG", sector: "Information Technology" },
  { ticker: "PVH", sector: "Consumer Discretionary" },
  { ticker: "QLYS", sector: "Information Technology" },
  { ticker: "R", sector: "Industrials" },
  { ticker: "RBA", sector: "Industrials" },
  { ticker: "RBC", sector: "Industrials" },
  { ticker: "REXR", sector: "Real Estate" },
  { ticker: "RGA", sector: "Financials" },
  { ticker: "RGEN", sector: "Health Care" },
  { ticker: "RGLD", sector: "Materials" },
  { ticker: "RH", sector: "Consumer Discretionary" },
  { ticker: "RLI", sector: "Financials" },
  { ticker: "RMBS", sector: "Information Technology" },
  { ticker: "RNR", sector: "Financials" },
  { ticker: "ROIV", sector: "Health Care" },
  { ticker: "RPM", sector: "Materials" },
  { ticker: "RRC", sector: "Energy" },
  { ticker: "RRX", sector: "Industrials" },
  { ticker: "RS", sector: "Materials" },
  { ticker: "RYAN", sector: "Financials" },
  { ticker: "RYN", sector: "Real Estate" },
  { ticker: "SAIA", sector: "Industrials" },
  { ticker: "SAIC", sector: "Industrials" },
  { ticker: "SAM", sector: "Consumer Staples" },
  { ticker: "SARO", sector: "Industrials" },
  { ticker: "SBRA", sector: "Real Estate" },
  { ticker: "SCI", sector: "Consumer Discretionary" },
  { ticker: "SEIC", sector: "Financials" },
  { ticker: "SF", sector: "Financials" },
  { ticker: "SFM", sector: "Consumer Staples" },
  { ticker: "SGI", sector: "Consumer Discretionary" },
  { ticker: "SHC", sector: "Health Care" },
  { ticker: "SIGI", sector: "Financials" },
  { ticker: "SITM", sector: "Information Technology" },
  { ticker: "SLAB", sector: "Information Technology" },
  { ticker: "SLGN", sector: "Materials" },
  { ticker: "SLM", sector: "Financials" },
  { ticker: "SMG", sector: "Materials" },
  { ticker: "SNX", sector: "Information Technology" },
  { ticker: "SOLS", sector: "Materials" },
  { ticker: "SON", sector: "Materials" },
  { ticker: "SPXC", sector: "Industrials" },
  { ticker: "SR", sector: "Utilities" },
  { ticker: "SSB", sector: "Financials" },
  { ticker: "SSD", sector: "Industrials" },
  { ticker: "ST", sector: "Industrials" },
  { ticker: "STAG", sector: "Real Estate" },
  { ticker: "STRL", sector: "Industrials" },
  { ticker: "STWD", sector: "Financials" },
  { ticker: "SWX", sector: "Utilities" },
  { ticker: "SYNA", sector: "Information Technology" },
  { ticker: "TCBI", sector: "Financials" },
  { ticker: "TEX", sector: "Industrials" },
  { ticker: "THC", sector: "Health Care" },
  { ticker: "THG", sector: "Financials" },
  { ticker: "THO", sector: "Consumer Discretionary" },
  { ticker: "TKR", sector: "Industrials" },
  { ticker: "TLN", sector: "Utilities" },
  { ticker: "TMHC", sector: "Consumer Discretionary" },
  { ticker: "TNL", sector: "Consumer Discretionary" },
  { ticker: "TOL", sector: "Consumer Discretionary" },
  { ticker: "TREX", sector: "Industrials" },
  { ticker: "TRU", sector: "Industrials" },
  { ticker: "TTC", sector: "Industrials" },
  { ticker: "TTEK", sector: "Industrials" },
  { ticker: "TTMI", sector: "Information Technology" },
  { ticker: "TWLO", sector: "Information Technology" },
  { ticker: "TXNM", sector: "Utilities" },
  { ticker: "TXRH", sector: "Consumer Discretionary" },
  { ticker: "UBSI", sector: "Financials" },
  { ticker: "UFPI", sector: "Industrials" },
  { ticker: "UGI", sector: "Utilities" },
  { ticker: "ULS", sector: "Industrials" },
  { ticker: "UMBF", sector: "Financials" },
  { ticker: "UNM", sector: "Financials" },
  { ticker: "USFD", sector: "Consumer Staples" },
  { ticker: "UTHR", sector: "Health Care" },
  { ticker: "VAL", sector: "Energy" },
  { ticker: "VC", sector: "Consumer Discretionary" },
  { ticker: "VFC", sector: "Consumer Discretionary" },
  { ticker: "VICR", sector: "Industrials" },
  { ticker: "VLY", sector: "Financials" },
  { ticker: "VMI", sector: "Industrials" },
  { ticker: "VNO", sector: "Real Estate" },
  { ticker: "VNOM", sector: "Energy" },
  { ticker: "VNT", sector: "Information Technology" },
  { ticker: "VOYA", sector: "Financials" },
  { ticker: "VVV", sector: "Consumer Discretionary" },
  { ticker: "WAL", sector: "Financials" },
  { ticker: "WBS", sector: "Financials" },
  { ticker: "WCC", sector: "Industrials" },
  { ticker: "WEX", sector: "Financials" },
  { ticker: "WFRD", sector: "Energy" },
  { ticker: "WH", sector: "Consumer Discretionary" },
  { ticker: "WHR", sector: "Consumer Discretionary" },
  { ticker: "WING", sector: "Consumer Discretionary" },
  { ticker: "WLK", sector: "Materials" },
  { ticker: "WMG", sector: "Communication Services" },
  { ticker: "WMS", sector: "Industrials" },
  { ticker: "WPC", sector: "Real Estate" },
  { ticker: "WSO", sector: "Industrials" },
  { ticker: "WTFC", sector: "Financials" },
  { ticker: "WTRG", sector: "Utilities" },
  { ticker: "WTS", sector: "Industrials" },
  { ticker: "WWD", sector: "Industrials" },
  { ticker: "XPO", sector: "Industrials" },
  { ticker: "XRAY", sector: "Health Care" },
  { ticker: "YETI", sector: "Consumer Discretionary" },
  { ticker: "ZION", sector: "Financials" },
];
