export type SP500Company = import("@/lib/screener/cac40").ScreenableCompany;

export const SP500_COMPANIES: SP500Company[] = [
  // Communication Services
  { ticker: "GOOGL", sector: "Communication Services" },
  { ticker: "GOOG", sector: "Communication Services" },
  { ticker: "META", sector: "Communication Services" },
  { ticker: "NFLX", sector: "Communication Services" },
  { ticker: "DIS", sector: "Communication Services" },
  { ticker: "CMCSA", sector: "Communication Services" },
  { ticker: "T", sector: "Communication Services" },
  { ticker: "VZ", sector: "Communication Services" },
  { ticker: "TMUS", sector: "Communication Services" },
  { ticker: "CHTR", sector: "Communication Services" },
  { ticker: "EA", sector: "Communication Services" },
  { ticker: "WBD", sector: "Communication Services" },
  { ticker: "IPG", sector: "Communication Services" },
  { ticker: "OMC", sector: "Communication Services" },
  { ticker: "FOXA", sector: "Communication Services" },
  { ticker: "FOX", sector: "Communication Services" },
  { ticker: "LYV", sector: "Communication Services" },
  { ticker: "TTWO", sector: "Communication Services" },
  // Consumer Discretionary
  { ticker: "AMZN", sector: "Consumer Discretionary" },
  { ticker: "TSLA", sector: "Consumer Discretionary" },
  { ticker: "HD", sector: "Consumer Discretionary" },
  { ticker: "MCD", sector: "Consumer Discretionary" },
  { ticker: "NKE", sector: "Consumer Discretionary" },
  { ticker: "LOW", sector: "Consumer Discretionary" },
  { ticker: "SBUX", sector: "Consumer Discretionary" },
  { ticker: "TJX", sector: "Consumer Discretionary" },
  { ticker: "BKNG", sector: "Consumer Discretionary" },
  { ticker: "ORLY", sector: "Consumer Discretionary" },
  { ticker: "AZO", sector: "Consumer Discretionary" },
  { ticker: "GM", sector: "Consumer Discretionary" },
  { ticker: "F", sector: "Consumer Discretionary" },
  { ticker: "ROST", sector: "Consumer Discretionary" },
  { ticker: "MAR", sector: "Consumer Discretionary" },
  { ticker: "YUM", sector: "Consumer Discretionary" },
  { ticker: "DHI", sector: "Consumer Discretionary" },
  { ticker: "LEN", sector: "Consumer Discretionary" },
  { ticker: "PHM", sector: "Consumer Discretionary" },
  { ticker: "EBAY", sector: "Consumer Discretionary" },
  { ticker: "HLT", sector: "Consumer Discretionary" },
  { ticker: "CMG", sector: "Consumer Discretionary" },
  { ticker: "VFC", sector: "Consumer Discretionary" },
  { ticker: "RL", sector: "Consumer Discretionary" },
  { ticker: "TPR", sector: "Consumer Discretionary" },
  { ticker: "ULTA", sector: "Consumer Discretionary" },
  { ticker: "EXPE", sector: "Consumer Discretionary" },
  { ticker: "DRI", sector: "Consumer Discretionary" },
  { ticker: "MGM", sector: "Consumer Discretionary" },
  { ticker: "CZR", sector: "Consumer Discretionary" },
  // Consumer Staples
  { ticker: "WMT", sector: "Consumer Staples" },
  { ticker: "PG", sector: "Consumer Staples" },
  { ticker: "KO", sector: "Consumer Staples" },
  { ticker: "PEP", sector: "Consumer Staples" },
  { ticker: "COST", sector: "Consumer Staples" },
  { ticker: "PM", sector: "Consumer Staples" },
  { ticker: "MO", sector: "Consumer Staples" },
  { ticker: "MDLZ", sector: "Consumer Staples" },
  { ticker: "CL", sector: "Consumer Staples" },
  { ticker: "KMB", sector: "Consumer Staples" },
  { ticker: "GIS", sector: "Consumer Staples" },
  { ticker: "KHC", sector: "Consumer Staples" },
  { ticker: "HSY", sector: "Consumer Staples" },
  { ticker: "SYY", sector: "Consumer Staples" },
  { ticker: "ADM", sector: "Consumer Staples" },
  { ticker: "STZ", sector: "Consumer Staples" },
  { ticker: "KR", sector: "Consumer Staples" },
  { ticker: "TAP", sector: "Consumer Staples" },
  { ticker: "CAG", sector: "Consumer Staples" },
  { ticker: "MKC", sector: "Consumer Staples" },
  { ticker: "CHD", sector: "Consumer Staples" },
  { ticker: "CLX", sector: "Consumer Staples" },
  { ticker: "EL", sector: "Consumer Staples" },
  { ticker: "COTY", sector: "Consumer Staples" },
  // Energy
  { ticker: "XOM", sector: "Energy" },
  { ticker: "CVX", sector: "Energy" },
  { ticker: "COP", sector: "Energy" },
  { ticker: "EOG", sector: "Energy" },
  { ticker: "SLB", sector: "Energy" },
  { ticker: "MPC", sector: "Energy" },
  { ticker: "PSX", sector: "Energy" },
  { ticker: "VLO", sector: "Energy" },
  { ticker: "PR", sector: "Energy" },
  { ticker: "OXY", sector: "Energy" },
  { ticker: "DVN", sector: "Energy" },
  { ticker: "HAL", sector: "Energy" },
  { ticker: "BKR", sector: "Energy" },
  { ticker: "FANG", sector: "Energy" },
  { ticker: "HES", sector: "Energy" },
  { ticker: "APA", sector: "Energy" },
  { ticker: "MRO", sector: "Energy" },
  { ticker: "OKE", sector: "Energy" },
  { ticker: "WMB", sector: "Energy" },
  { ticker: "KMI", sector: "Energy" },
  // Financials
  { ticker: "BRK-B", sector: "Financials" },
  { ticker: "JPM", sector: "Financials" },
  { ticker: "BAC", sector: "Financials" },
  { ticker: "WFC", sector: "Financials" },
  { ticker: "MS", sector: "Financials" },
  { ticker: "GS", sector: "Financials" },
  { ticker: "BLK", sector: "Financials" },
  { ticker: "SCHW", sector: "Financials" },
  { ticker: "AXP", sector: "Financials" },
  { ticker: "C", sector: "Financials" },
  { ticker: "USB", sector: "Financials" },
  { ticker: "PNC", sector: "Financials" },
  { ticker: "TFC", sector: "Financials" },
  { ticker: "COF", sector: "Financials" },
  { ticker: "MCO", sector: "Financials" },
  { ticker: "SPGI", sector: "Financials" },
  { ticker: "ICE", sector: "Financials" },
  { ticker: "CME", sector: "Financials" },
  { ticker: "CB", sector: "Financials" },
  { ticker: "MMC", sector: "Financials" },
  { ticker: "AON", sector: "Financials" },
  { ticker: "MET", sector: "Financials" },
  { ticker: "PRU", sector: "Financials" },
  { ticker: "AFL", sector: "Financials" },
  { ticker: "TRV", sector: "Financials" },
  { ticker: "ALL", sector: "Financials" },
  { ticker: "AIG", sector: "Financials" },
  { ticker: "HIG", sector: "Financials" },
  { ticker: "STT", sector: "Financials" },
  { ticker: "BK", sector: "Financials" },
  // Health Care
  { ticker: "UNH", sector: "Health Care" },
  { ticker: "JNJ", sector: "Health Care" },
  { ticker: "LLY", sector: "Health Care" },
  { ticker: "ABBV", sector: "Health Care" },
  { ticker: "MRK", sector: "Health Care" },
  { ticker: "TMO", sector: "Health Care" },
  { ticker: "ABT", sector: "Health Care" },
  { ticker: "DHR", sector: "Health Care" },
  { ticker: "BMY", sector: "Health Care" },
  { ticker: "AMGN", sector: "Health Care" },
  { ticker: "PFE", sector: "Health Care" },
  { ticker: "GILD", sector: "Health Care" },
  { ticker: "CVS", sector: "Health Care" },
  { ticker: "ISRG", sector: "Health Care" },
  { ticker: "MDT", sector: "Health Care" },
  { ticker: "SYK", sector: "Health Care" },
  { ticker: "BDX", sector: "Health Care" },
  { ticker: "ZTS", sector: "Health Care" },
  { ticker: "REGN", sector: "Health Care" },
  { ticker: "VRTX", sector: "Health Care" },
  { ticker: "CI", sector: "Health Care" },
  { ticker: "ELV", sector: "Health Care" },
  { ticker: "HUM", sector: "Health Care" },
  { ticker: "CNC", sector: "Health Care" },
  { ticker: "MCK", sector: "Health Care" },
  { ticker: "CAH", sector: "Health Care" },
  { ticker: "ABC", sector: "Health Care" },
  { ticker: "HCA", sector: "Health Care" },
  { ticker: "IDXX", sector: "Health Care" },
  { ticker: "A", sector: "Health Care" },
  // Industrials
  { ticker: "UPS", sector: "Industrials" },
  { ticker: "HON", sector: "Industrials" },
  { ticker: "UNP", sector: "Industrials" },
  { ticker: "CAT", sector: "Industrials" },
  { ticker: "BA", sector: "Industrials" },
  { ticker: "DE", sector: "Industrials" },
  { ticker: "RTX", sector: "Industrials" },
  { ticker: "LMT", sector: "Industrials" },
  { ticker: "GE", sector: "Industrials" },
  { ticker: "MMM", sector: "Industrials" },
  { ticker: "ITW", sector: "Industrials" },
  { ticker: "EMR", sector: "Industrials" },
  { ticker: "FDX", sector: "Industrials" },
  { ticker: "NSC", sector: "Industrials" },
  { ticker: "CSX", sector: "Industrials" },
  { ticker: "GD", sector: "Industrials" },
  { ticker: "NOC", sector: "Industrials" },
  { ticker: "LHX", sector: "Industrials" },
  { ticker: "TT", sector: "Industrials" },
  { ticker: "CMI", sector: "Industrials" },
  { ticker: "PCAR", sector: "Industrials" },
  { ticker: "ETN", sector: "Industrials" },
  { ticker: "PH", sector: "Industrials" },
  { ticker: "ROK", sector: "Industrials" },
  { ticker: "SWK", sector: "Industrials" },
  { ticker: "XYL", sector: "Industrials" },
  { ticker: "AME", sector: "Industrials" },
  { ticker: "GWW", sector: "Industrials" },
  { ticker: "CARR", sector: "Industrials" },
  { ticker: "OTIS", sector: "Industrials" },
  // Information Technology
  { ticker: "AAPL", sector: "Information Technology" },
  { ticker: "MSFT", sector: "Information Technology" },
  { ticker: "NVDA", sector: "Information Technology" },
  { ticker: "AVGO", sector: "Information Technology" },
  { ticker: "ORCL", sector: "Information Technology" },
  { ticker: "CRM", sector: "Information Technology" },
  { ticker: "CSCO", sector: "Information Technology" },
  { ticker: "ACN", sector: "Information Technology" },
  { ticker: "IBM", sector: "Information Technology" },
  { ticker: "NOW", sector: "Information Technology" },
  { ticker: "ADBE", sector: "Information Technology" },
  { ticker: "QCOM", sector: "Information Technology" },
  { ticker: "TXN", sector: "Information Technology" },
  { ticker: "INTC", sector: "Information Technology" },
  { ticker: "AMD", sector: "Information Technology" },
  { ticker: "AMAT", sector: "Information Technology" },
  { ticker: "MU", sector: "Information Technology" },
  { ticker: "LRCX", sector: "Information Technology" },
  { ticker: "KLAC", sector: "Information Technology" },
  { ticker: "ADI", sector: "Information Technology" },
  { ticker: "APH", sector: "Information Technology" },
  { ticker: "MSI", sector: "Information Technology" },
  { ticker: "CDNS", sector: "Information Technology" },
  { ticker: "SNPS", sector: "Information Technology" },
  { ticker: "FTNT", sector: "Information Technology" },
  { ticker: "HPQ", sector: "Information Technology" },
  { ticker: "HPE", sector: "Information Technology" },
  { ticker: "DELL", sector: "Information Technology" },
  { ticker: "WDC", sector: "Information Technology" },
  { ticker: "STX", sector: "Information Technology" },
  // Materials
  { ticker: "LIN", sector: "Materials" },
  { ticker: "APD", sector: "Materials" },
  { ticker: "SHW", sector: "Materials" },
  { ticker: "FCX", sector: "Materials" },
  { ticker: "NEM", sector: "Materials" },
  { ticker: "ECL", sector: "Materials" },
  { ticker: "PPG", sector: "Materials" },
  { ticker: "DD", sector: "Materials" },
  { ticker: "DOW", sector: "Materials" },
  { ticker: "NUE", sector: "Materials" },
  { ticker: "VMC", sector: "Materials" },
  { ticker: "MLM", sector: "Materials" },
  { ticker: "IFF", sector: "Materials" },
  { ticker: "CE", sector: "Materials" },
  { ticker: "ALB", sector: "Materials" },
  { ticker: "CF", sector: "Materials" },
  { ticker: "MOS", sector: "Materials" },
  { ticker: "PKG", sector: "Materials" },
  { ticker: "IP", sector: "Materials" },
  { ticker: "SW", sector: "Materials" },
  // Real Estate
  { ticker: "AMT", sector: "Real Estate" },
  { ticker: "PLD", sector: "Real Estate" },
  { ticker: "CCI", sector: "Real Estate" },
  { ticker: "EQIX", sector: "Real Estate" },
  { ticker: "PSA", sector: "Real Estate" },
  { ticker: "O", sector: "Real Estate" },
  { ticker: "WELL", sector: "Real Estate" },
  { ticker: "DLR", sector: "Real Estate" },
  { ticker: "SPG", sector: "Real Estate" },
  { ticker: "EQR", sector: "Real Estate" },
  { ticker: "AVB", sector: "Real Estate" },
  { ticker: "ARE", sector: "Real Estate" },
  { ticker: "BXP", sector: "Real Estate" },
  { ticker: "VTR", sector: "Real Estate" },
  { ticker: "INVH", sector: "Real Estate" },
  // Utilities
  { ticker: "NEE", sector: "Utilities" },
  { ticker: "DUK", sector: "Utilities" },
  { ticker: "SO", sector: "Utilities" },
  { ticker: "D", sector: "Utilities" },
  { ticker: "AEP", sector: "Utilities" },
  { ticker: "EXC", sector: "Utilities" },
  { ticker: "XEL", sector: "Utilities" },
  { ticker: "SRE", sector: "Utilities" },
  { ticker: "PCG", sector: "Utilities" },
  { ticker: "ED", sector: "Utilities" },
  { ticker: "WEC", sector: "Utilities" },
  { ticker: "ES", sector: "Utilities" },
  { ticker: "ETR", sector: "Utilities" },
  { ticker: "AWK", sector: "Utilities" },
  { ticker: "PPL", sector: "Utilities" },
  { ticker: "EIX", sector: "Utilities" },
  { ticker: "CMS", sector: "Utilities" },
  { ticker: "CNP", sector: "Utilities" },
  { ticker: "AES", sector: "Utilities" },
  { ticker: "NI", sector: "Utilities" },
];

export const SP500_TICKERS = SP500_COMPANIES.map((c) => c.ticker);

export function getSectorForTicker(ticker: string): string | undefined {
  return SP500_COMPANIES.find((c) => c.ticker === ticker)?.sector;
}
