import type { ScreenableCompany } from "@/lib/screener/cac40";

// Full S&P 500 constituent list sourced from Wikipedia's
// "List of S&P 500 companies" (July 2026). 502 constituents with GICS
// sectors; class-share tickers use Yahoo's dash form (BRK-B, BF-B).
export const SP500_COMPANIES: ScreenableCompany[] = [
  // ── Communication Services ──
  { ticker: "CHTR", sector: "Communication Services" },
  { ticker: "CMCSA", sector: "Communication Services" },
  { ticker: "DIS", sector: "Communication Services" },
  { ticker: "EA", sector: "Communication Services" },
  { ticker: "ECHO", sector: "Communication Services" },
  { ticker: "FOX", sector: "Communication Services" },
  { ticker: "FOXA", sector: "Communication Services" },
  { ticker: "GOOG", sector: "Communication Services" },
  { ticker: "GOOGL", sector: "Communication Services" },
  { ticker: "LYV", sector: "Communication Services" },
  { ticker: "META", sector: "Communication Services" },
  { ticker: "NFLX", sector: "Communication Services" },
  { ticker: "NWS", sector: "Communication Services" },
  { ticker: "NWSA", sector: "Communication Services" },
  { ticker: "OMC", sector: "Communication Services" },
  { ticker: "PSKY", sector: "Communication Services" },
  { ticker: "T", sector: "Communication Services" },
  { ticker: "TKO", sector: "Communication Services" },
  { ticker: "TMUS", sector: "Communication Services" },
  { ticker: "TTD", sector: "Communication Services" },
  { ticker: "TTWO", sector: "Communication Services" },
  { ticker: "VZ", sector: "Communication Services" },
  { ticker: "WBD", sector: "Communication Services" },

  // ── Consumer Discretionary ──
  { ticker: "ABNB", sector: "Consumer Discretionary" },
  { ticker: "AMZN", sector: "Consumer Discretionary" },
  { ticker: "APTV", sector: "Consumer Discretionary" },
  { ticker: "AZO", sector: "Consumer Discretionary" },
  { ticker: "BBY", sector: "Consumer Discretionary" },
  { ticker: "BKNG", sector: "Consumer Discretionary" },
  { ticker: "CCL", sector: "Consumer Discretionary" },
  { ticker: "CMG", sector: "Consumer Discretionary" },
  { ticker: "CVNA", sector: "Consumer Discretionary" },
  { ticker: "DASH", sector: "Consumer Discretionary" },
  { ticker: "DECK", sector: "Consumer Discretionary" },
  { ticker: "DHI", sector: "Consumer Discretionary" },
  { ticker: "DPZ", sector: "Consumer Discretionary" },
  { ticker: "DRI", sector: "Consumer Discretionary" },
  { ticker: "EBAY", sector: "Consumer Discretionary" },
  { ticker: "EXPE", sector: "Consumer Discretionary" },
  { ticker: "F", sector: "Consumer Discretionary" },
  { ticker: "GM", sector: "Consumer Discretionary" },
  { ticker: "GPC", sector: "Consumer Discretionary" },
  { ticker: "GRMN", sector: "Consumer Discretionary" },
  { ticker: "HAS", sector: "Consumer Discretionary" },
  { ticker: "HD", sector: "Consumer Discretionary" },
  { ticker: "HLT", sector: "Consumer Discretionary" },
  { ticker: "LEN", sector: "Consumer Discretionary" },
  { ticker: "LOW", sector: "Consumer Discretionary" },
  { ticker: "LULU", sector: "Consumer Discretionary" },
  { ticker: "LVS", sector: "Consumer Discretionary" },
  { ticker: "MAR", sector: "Consumer Discretionary" },
  { ticker: "MCD", sector: "Consumer Discretionary" },
  { ticker: "MGM", sector: "Consumer Discretionary" },
  { ticker: "NCLH", sector: "Consumer Discretionary" },
  { ticker: "NKE", sector: "Consumer Discretionary" },
  { ticker: "NVR", sector: "Consumer Discretionary" },
  { ticker: "ORLY", sector: "Consumer Discretionary" },
  { ticker: "PHM", sector: "Consumer Discretionary" },
  { ticker: "RCL", sector: "Consumer Discretionary" },
  { ticker: "RL", sector: "Consumer Discretionary" },
  { ticker: "ROST", sector: "Consumer Discretionary" },
  { ticker: "SBUX", sector: "Consumer Discretionary" },
  { ticker: "TJX", sector: "Consumer Discretionary" },
  { ticker: "TPR", sector: "Consumer Discretionary" },
  { ticker: "TSCO", sector: "Consumer Discretionary" },
  { ticker: "TSLA", sector: "Consumer Discretionary" },
  { ticker: "ULTA", sector: "Consumer Discretionary" },
  { ticker: "WSM", sector: "Consumer Discretionary" },
  { ticker: "WYNN", sector: "Consumer Discretionary" },
  { ticker: "YUM", sector: "Consumer Discretionary" },

  // ── Consumer Staples ──
  { ticker: "ADM", sector: "Consumer Staples" },
  { ticker: "BF-B", sector: "Consumer Staples" },
  { ticker: "BG", sector: "Consumer Staples" },
  { ticker: "CASY", sector: "Consumer Staples" },
  { ticker: "CHD", sector: "Consumer Staples" },
  { ticker: "CL", sector: "Consumer Staples" },
  { ticker: "CLX", sector: "Consumer Staples" },
  { ticker: "COST", sector: "Consumer Staples" },
  { ticker: "DG", sector: "Consumer Staples" },
  { ticker: "DLTR", sector: "Consumer Staples" },
  { ticker: "EL", sector: "Consumer Staples" },
  { ticker: "GIS", sector: "Consumer Staples" },
  { ticker: "HRL", sector: "Consumer Staples" },
  { ticker: "HSY", sector: "Consumer Staples" },
  { ticker: "KDP", sector: "Consumer Staples" },
  { ticker: "KHC", sector: "Consumer Staples" },
  { ticker: "KMB", sector: "Consumer Staples" },
  { ticker: "KO", sector: "Consumer Staples" },
  { ticker: "KR", sector: "Consumer Staples" },
  { ticker: "KVUE", sector: "Consumer Staples" },
  { ticker: "MDLZ", sector: "Consumer Staples" },
  { ticker: "MKC", sector: "Consumer Staples" },
  { ticker: "MNST", sector: "Consumer Staples" },
  { ticker: "MO", sector: "Consumer Staples" },
  { ticker: "PEP", sector: "Consumer Staples" },
  { ticker: "PG", sector: "Consumer Staples" },
  { ticker: "PM", sector: "Consumer Staples" },
  { ticker: "SJM", sector: "Consumer Staples" },
  { ticker: "STZ", sector: "Consumer Staples" },
  { ticker: "SYY", sector: "Consumer Staples" },
  { ticker: "TAP", sector: "Consumer Staples" },
  { ticker: "TGT", sector: "Consumer Staples" },
  { ticker: "TSN", sector: "Consumer Staples" },
  { ticker: "WMT", sector: "Consumer Staples" },

  // ── Energy ──
  { ticker: "APA", sector: "Energy" },
  { ticker: "BKR", sector: "Energy" },
  { ticker: "COP", sector: "Energy" },
  { ticker: "CVX", sector: "Energy" },
  { ticker: "DVN", sector: "Energy" },
  { ticker: "EOG", sector: "Energy" },
  { ticker: "EQT", sector: "Energy" },
  { ticker: "EXE", sector: "Energy" },
  { ticker: "FANG", sector: "Energy" },
  { ticker: "HAL", sector: "Energy" },
  { ticker: "KMI", sector: "Energy" },
  { ticker: "MPC", sector: "Energy" },
  { ticker: "OKE", sector: "Energy" },
  { ticker: "OXY", sector: "Energy" },
  { ticker: "PSX", sector: "Energy" },
  { ticker: "SLB", sector: "Energy" },
  { ticker: "TPL", sector: "Energy" },
  { ticker: "TRGP", sector: "Energy" },
  { ticker: "VLO", sector: "Energy" },
  { ticker: "WMB", sector: "Energy" },
  { ticker: "XOM", sector: "Energy" },

  // ── Financials ──
  { ticker: "ACGL", sector: "Financials" },
  { ticker: "AFL", sector: "Financials" },
  { ticker: "AIG", sector: "Financials" },
  { ticker: "AIZ", sector: "Financials" },
  { ticker: "AJG", sector: "Financials" },
  { ticker: "ALL", sector: "Financials" },
  { ticker: "AMP", sector: "Financials" },
  { ticker: "AON", sector: "Financials" },
  { ticker: "APO", sector: "Financials" },
  { ticker: "ARES", sector: "Financials" },
  { ticker: "AXP", sector: "Financials" },
  { ticker: "BAC", sector: "Financials" },
  { ticker: "BEN", sector: "Financials" },
  { ticker: "BLK", sector: "Financials" },
  { ticker: "BNY", sector: "Financials" },
  { ticker: "BRK-B", sector: "Financials" },
  { ticker: "BRO", sector: "Financials" },
  { ticker: "BX", sector: "Financials" },
  { ticker: "C", sector: "Financials" },
  { ticker: "CB", sector: "Financials" },
  { ticker: "CFG", sector: "Financials" },
  { ticker: "CINF", sector: "Financials" },
  { ticker: "CME", sector: "Financials" },
  { ticker: "COF", sector: "Financials" },
  { ticker: "COIN", sector: "Financials" },
  { ticker: "CPAY", sector: "Financials" },
  { ticker: "EG", sector: "Financials" },
  { ticker: "ERIE", sector: "Financials" },
  { ticker: "FDS", sector: "Financials" },
  { ticker: "FIS", sector: "Financials" },
  { ticker: "FISV", sector: "Financials" },
  { ticker: "FITB", sector: "Financials" },
  { ticker: "GL", sector: "Financials" },
  { ticker: "GPN", sector: "Financials" },
  { ticker: "GS", sector: "Financials" },
  { ticker: "HBAN", sector: "Financials" },
  { ticker: "HIG", sector: "Financials" },
  { ticker: "HOOD", sector: "Financials" },
  { ticker: "IBKR", sector: "Financials" },
  { ticker: "ICE", sector: "Financials" },
  { ticker: "IVZ", sector: "Financials" },
  { ticker: "JKHY", sector: "Financials" },
  { ticker: "JPM", sector: "Financials" },
  { ticker: "KEY", sector: "Financials" },
  { ticker: "KKR", sector: "Financials" },
  { ticker: "L", sector: "Financials" },
  { ticker: "MA", sector: "Financials" },
  { ticker: "MCO", sector: "Financials" },
  { ticker: "MET", sector: "Financials" },
  { ticker: "MRSH", sector: "Financials" },
  { ticker: "MS", sector: "Financials" },
  { ticker: "MSCI", sector: "Financials" },
  { ticker: "MTB", sector: "Financials" },
  { ticker: "NDAQ", sector: "Financials" },
  { ticker: "NTRS", sector: "Financials" },
  { ticker: "PFG", sector: "Financials" },
  { ticker: "PGR", sector: "Financials" },
  { ticker: "PNC", sector: "Financials" },
  { ticker: "PRU", sector: "Financials" },
  { ticker: "PYPL", sector: "Financials" },
  { ticker: "RF", sector: "Financials" },
  { ticker: "RJF", sector: "Financials" },
  { ticker: "SCHW", sector: "Financials" },
  { ticker: "SPGI", sector: "Financials" },
  { ticker: "STT", sector: "Financials" },
  { ticker: "SYF", sector: "Financials" },
  { ticker: "TFC", sector: "Financials" },
  { ticker: "TROW", sector: "Financials" },
  { ticker: "TRV", sector: "Financials" },
  { ticker: "USB", sector: "Financials" },
  { ticker: "V", sector: "Financials" },
  { ticker: "WFC", sector: "Financials" },
  { ticker: "WRB", sector: "Financials" },
  { ticker: "WTW", sector: "Financials" },
  { ticker: "XYZ", sector: "Financials" },

  // ── Health Care ──
  { ticker: "A", sector: "Health Care" },
  { ticker: "ABBV", sector: "Health Care" },
  { ticker: "ABT", sector: "Health Care" },
  { ticker: "ALGN", sector: "Health Care" },
  { ticker: "AMGN", sector: "Health Care" },
  { ticker: "BAX", sector: "Health Care" },
  { ticker: "BDX", sector: "Health Care" },
  { ticker: "BIIB", sector: "Health Care" },
  { ticker: "BMY", sector: "Health Care" },
  { ticker: "BSX", sector: "Health Care" },
  { ticker: "CAH", sector: "Health Care" },
  { ticker: "CI", sector: "Health Care" },
  { ticker: "CNC", sector: "Health Care" },
  { ticker: "COO", sector: "Health Care" },
  { ticker: "COR", sector: "Health Care" },
  { ticker: "CRL", sector: "Health Care" },
  { ticker: "CVS", sector: "Health Care" },
  { ticker: "DGX", sector: "Health Care" },
  { ticker: "DHR", sector: "Health Care" },
  { ticker: "DVA", sector: "Health Care" },
  { ticker: "DXCM", sector: "Health Care" },
  { ticker: "ELV", sector: "Health Care" },
  { ticker: "EW", sector: "Health Care" },
  { ticker: "GEHC", sector: "Health Care" },
  { ticker: "GILD", sector: "Health Care" },
  { ticker: "HCA", sector: "Health Care" },
  { ticker: "HSIC", sector: "Health Care" },
  { ticker: "HUM", sector: "Health Care" },
  { ticker: "IDXX", sector: "Health Care" },
  { ticker: "INCY", sector: "Health Care" },
  { ticker: "IQV", sector: "Health Care" },
  { ticker: "ISRG", sector: "Health Care" },
  { ticker: "JNJ", sector: "Health Care" },
  { ticker: "LH", sector: "Health Care" },
  { ticker: "LLY", sector: "Health Care" },
  { ticker: "MCK", sector: "Health Care" },
  { ticker: "MDT", sector: "Health Care" },
  { ticker: "MRK", sector: "Health Care" },
  { ticker: "MRNA", sector: "Health Care" },
  { ticker: "MTD", sector: "Health Care" },
  { ticker: "PFE", sector: "Health Care" },
  { ticker: "PODD", sector: "Health Care" },
  { ticker: "REGN", sector: "Health Care" },
  { ticker: "RMD", sector: "Health Care" },
  { ticker: "RVTY", sector: "Health Care" },
  { ticker: "SOLV", sector: "Health Care" },
  { ticker: "STE", sector: "Health Care" },
  { ticker: "SYK", sector: "Health Care" },
  { ticker: "TECH", sector: "Health Care" },
  { ticker: "TMO", sector: "Health Care" },
  { ticker: "UHS", sector: "Health Care" },
  { ticker: "UNH", sector: "Health Care" },
  { ticker: "VEEV", sector: "Health Care" },
  { ticker: "VRTX", sector: "Health Care" },
  { ticker: "VTRS", sector: "Health Care" },
  { ticker: "WAT", sector: "Health Care" },
  { ticker: "WST", sector: "Health Care" },
  { ticker: "ZBH", sector: "Health Care" },
  { ticker: "ZTS", sector: "Health Care" },

  // ── Industrials ──
  { ticker: "ADP", sector: "Industrials" },
  { ticker: "ALLE", sector: "Industrials" },
  { ticker: "AME", sector: "Industrials" },
  { ticker: "AOS", sector: "Industrials" },
  { ticker: "AXON", sector: "Industrials" },
  { ticker: "BA", sector: "Industrials" },
  { ticker: "BLDR", sector: "Industrials" },
  { ticker: "BR", sector: "Industrials" },
  { ticker: "CARR", sector: "Industrials" },
  { ticker: "CAT", sector: "Industrials" },
  { ticker: "CHRW", sector: "Industrials" },
  { ticker: "CMI", sector: "Industrials" },
  { ticker: "CPRT", sector: "Industrials" },
  { ticker: "CSX", sector: "Industrials" },
  { ticker: "CTAS", sector: "Industrials" },
  { ticker: "DAL", sector: "Industrials" },
  { ticker: "DE", sector: "Industrials" },
  { ticker: "DOV", sector: "Industrials" },
  { ticker: "EFX", sector: "Industrials" },
  { ticker: "EME", sector: "Industrials" },
  { ticker: "EMR", sector: "Industrials" },
  { ticker: "ETN", sector: "Industrials" },
  { ticker: "EXPD", sector: "Industrials" },
  { ticker: "FAST", sector: "Industrials" },
  { ticker: "FDX", sector: "Industrials" },
  { ticker: "FDXF", sector: "Industrials" },
  { ticker: "FIX", sector: "Industrials" },
  { ticker: "FTV", sector: "Industrials" },
  { ticker: "GD", sector: "Industrials" },
  { ticker: "GE", sector: "Industrials" },
  { ticker: "GEV", sector: "Industrials" },
  { ticker: "GNRC", sector: "Industrials" },
  { ticker: "GWW", sector: "Industrials" },
  { ticker: "HII", sector: "Industrials" },
  { ticker: "HON", sector: "Industrials" },
  { ticker: "HONA", sector: "Industrials" },
  { ticker: "HUBB", sector: "Industrials" },
  { ticker: "HWM", sector: "Industrials" },
  { ticker: "IEX", sector: "Industrials" },
  { ticker: "IR", sector: "Industrials" },
  { ticker: "ITW", sector: "Industrials" },
  { ticker: "J", sector: "Industrials" },
  { ticker: "JBHT", sector: "Industrials" },
  { ticker: "JCI", sector: "Industrials" },
  { ticker: "LDOS", sector: "Industrials" },
  { ticker: "LHX", sector: "Industrials" },
  { ticker: "LII", sector: "Industrials" },
  { ticker: "LMT", sector: "Industrials" },
  { ticker: "LUV", sector: "Industrials" },
  { ticker: "MAS", sector: "Industrials" },
  { ticker: "MMM", sector: "Industrials" },
  { ticker: "NDSN", sector: "Industrials" },
  { ticker: "NOC", sector: "Industrials" },
  { ticker: "NSC", sector: "Industrials" },
  { ticker: "ODFL", sector: "Industrials" },
  { ticker: "OTIS", sector: "Industrials" },
  { ticker: "PAYX", sector: "Industrials" },
  { ticker: "PCAR", sector: "Industrials" },
  { ticker: "PH", sector: "Industrials" },
  { ticker: "PNR", sector: "Industrials" },
  { ticker: "PWR", sector: "Industrials" },
  { ticker: "ROK", sector: "Industrials" },
  { ticker: "ROL", sector: "Industrials" },
  { ticker: "RSG", sector: "Industrials" },
  { ticker: "RTX", sector: "Industrials" },
  { ticker: "SNA", sector: "Industrials" },
  { ticker: "SWK", sector: "Industrials" },
  { ticker: "TDG", sector: "Industrials" },
  { ticker: "TT", sector: "Industrials" },
  { ticker: "TXT", sector: "Industrials" },
  { ticker: "UAL", sector: "Industrials" },
  { ticker: "UBER", sector: "Industrials" },
  { ticker: "UNP", sector: "Industrials" },
  { ticker: "UPS", sector: "Industrials" },
  { ticker: "URI", sector: "Industrials" },
  { ticker: "VLTO", sector: "Industrials" },
  { ticker: "VRSK", sector: "Industrials" },
  { ticker: "VRT", sector: "Industrials" },
  { ticker: "WAB", sector: "Industrials" },
  { ticker: "WM", sector: "Industrials" },
  { ticker: "XYL", sector: "Industrials" },

  // ── Information Technology ──
  { ticker: "AAPL", sector: "Information Technology" },
  { ticker: "ACN", sector: "Information Technology" },
  { ticker: "ADBE", sector: "Information Technology" },
  { ticker: "ADI", sector: "Information Technology" },
  { ticker: "ADSK", sector: "Information Technology" },
  { ticker: "AKAM", sector: "Information Technology" },
  { ticker: "AMAT", sector: "Information Technology" },
  { ticker: "AMD", sector: "Information Technology" },
  { ticker: "ANET", sector: "Information Technology" },
  { ticker: "APH", sector: "Information Technology" },
  { ticker: "APP", sector: "Information Technology" },
  { ticker: "AVGO", sector: "Information Technology" },
  { ticker: "CDNS", sector: "Information Technology" },
  { ticker: "CDW", sector: "Information Technology" },
  { ticker: "CIEN", sector: "Information Technology" },
  { ticker: "COHR", sector: "Information Technology" },
  { ticker: "CRM", sector: "Information Technology" },
  { ticker: "CRWD", sector: "Information Technology" },
  { ticker: "CSCO", sector: "Information Technology" },
  { ticker: "CTSH", sector: "Information Technology" },
  { ticker: "DDOG", sector: "Information Technology" },
  { ticker: "DELL", sector: "Information Technology" },
  { ticker: "FFIV", sector: "Information Technology" },
  { ticker: "FICO", sector: "Information Technology" },
  { ticker: "FLEX", sector: "Information Technology" },
  { ticker: "FSLR", sector: "Information Technology" },
  { ticker: "FTNT", sector: "Information Technology" },
  { ticker: "GDDY", sector: "Information Technology" },
  { ticker: "GEN", sector: "Information Technology" },
  { ticker: "GLW", sector: "Information Technology" },
  { ticker: "HPE", sector: "Information Technology" },
  { ticker: "HPQ", sector: "Information Technology" },
  { ticker: "IBM", sector: "Information Technology" },
  { ticker: "INTC", sector: "Information Technology" },
  { ticker: "INTU", sector: "Information Technology" },
  { ticker: "IT", sector: "Information Technology" },
  { ticker: "JBL", sector: "Information Technology" },
  { ticker: "KEYS", sector: "Information Technology" },
  { ticker: "KLAC", sector: "Information Technology" },
  { ticker: "LITE", sector: "Information Technology" },
  { ticker: "LRCX", sector: "Information Technology" },
  { ticker: "MCHP", sector: "Information Technology" },
  { ticker: "MPWR", sector: "Information Technology" },
  { ticker: "MRVL", sector: "Information Technology" },
  { ticker: "MSFT", sector: "Information Technology" },
  { ticker: "MSI", sector: "Information Technology" },
  { ticker: "MU", sector: "Information Technology" },
  { ticker: "NOW", sector: "Information Technology" },
  { ticker: "NTAP", sector: "Information Technology" },
  { ticker: "NVDA", sector: "Information Technology" },
  { ticker: "NXPI", sector: "Information Technology" },
  { ticker: "ON", sector: "Information Technology" },
  { ticker: "ORCL", sector: "Information Technology" },
  { ticker: "PANW", sector: "Information Technology" },
  { ticker: "PLTR", sector: "Information Technology" },
  { ticker: "PTC", sector: "Information Technology" },
  { ticker: "Q", sector: "Information Technology" },
  { ticker: "QCOM", sector: "Information Technology" },
  { ticker: "ROP", sector: "Information Technology" },
  { ticker: "SMCI", sector: "Information Technology" },
  { ticker: "SNDK", sector: "Information Technology" },
  { ticker: "SNPS", sector: "Information Technology" },
  { ticker: "STX", sector: "Information Technology" },
  { ticker: "SWKS", sector: "Information Technology" },
  { ticker: "TDY", sector: "Information Technology" },
  { ticker: "TEL", sector: "Information Technology" },
  { ticker: "TER", sector: "Information Technology" },
  { ticker: "TRMB", sector: "Information Technology" },
  { ticker: "TXN", sector: "Information Technology" },
  { ticker: "TYL", sector: "Information Technology" },
  { ticker: "VRSN", sector: "Information Technology" },
  { ticker: "WDAY", sector: "Information Technology" },
  { ticker: "WDC", sector: "Information Technology" },
  { ticker: "ZBRA", sector: "Information Technology" },

  // ── Materials ──
  { ticker: "ALB", sector: "Materials" },
  { ticker: "AMCR", sector: "Materials" },
  { ticker: "APD", sector: "Materials" },
  { ticker: "AVY", sector: "Materials" },
  { ticker: "BALL", sector: "Materials" },
  { ticker: "CF", sector: "Materials" },
  { ticker: "CRH", sector: "Materials" },
  { ticker: "CTVA", sector: "Materials" },
  { ticker: "DD", sector: "Materials" },
  { ticker: "DOW", sector: "Materials" },
  { ticker: "ECL", sector: "Materials" },
  { ticker: "FCX", sector: "Materials" },
  { ticker: "IFF", sector: "Materials" },
  { ticker: "IP", sector: "Materials" },
  { ticker: "LIN", sector: "Materials" },
  { ticker: "LYB", sector: "Materials" },
  { ticker: "MLM", sector: "Materials" },
  { ticker: "MOS", sector: "Materials" },
  { ticker: "NEM", sector: "Materials" },
  { ticker: "NUE", sector: "Materials" },
  { ticker: "PKG", sector: "Materials" },
  { ticker: "PPG", sector: "Materials" },
  { ticker: "SHW", sector: "Materials" },
  { ticker: "STLD", sector: "Materials" },
  { ticker: "SW", sector: "Materials" },
  { ticker: "VMC", sector: "Materials" },

  // ── Real Estate ──
  { ticker: "AMT", sector: "Real Estate" },
  { ticker: "ARE", sector: "Real Estate" },
  { ticker: "AVB", sector: "Real Estate" },
  { ticker: "BXP", sector: "Real Estate" },
  { ticker: "CBRE", sector: "Real Estate" },
  { ticker: "CCI", sector: "Real Estate" },
  { ticker: "CPT", sector: "Real Estate" },
  { ticker: "CSGP", sector: "Real Estate" },
  { ticker: "DLR", sector: "Real Estate" },
  { ticker: "DOC", sector: "Real Estate" },
  { ticker: "EQIX", sector: "Real Estate" },
  { ticker: "EQR", sector: "Real Estate" },
  { ticker: "ESS", sector: "Real Estate" },
  { ticker: "EXR", sector: "Real Estate" },
  { ticker: "FRT", sector: "Real Estate" },
  { ticker: "HST", sector: "Real Estate" },
  { ticker: "INVH", sector: "Real Estate" },
  { ticker: "IRM", sector: "Real Estate" },
  { ticker: "KIM", sector: "Real Estate" },
  { ticker: "MAA", sector: "Real Estate" },
  { ticker: "O", sector: "Real Estate" },
  { ticker: "PLD", sector: "Real Estate" },
  { ticker: "PSA", sector: "Real Estate" },
  { ticker: "REG", sector: "Real Estate" },
  { ticker: "SBAC", sector: "Real Estate" },
  { ticker: "SPG", sector: "Real Estate" },
  { ticker: "UDR", sector: "Real Estate" },
  { ticker: "VICI", sector: "Real Estate" },
  { ticker: "VTR", sector: "Real Estate" },
  { ticker: "WELL", sector: "Real Estate" },
  { ticker: "WY", sector: "Real Estate" },

  // ── Utilities ──
  { ticker: "AEE", sector: "Utilities" },
  { ticker: "AEP", sector: "Utilities" },
  { ticker: "AES", sector: "Utilities" },
  { ticker: "ATO", sector: "Utilities" },
  { ticker: "AWK", sector: "Utilities" },
  { ticker: "CEG", sector: "Utilities" },
  { ticker: "CMS", sector: "Utilities" },
  { ticker: "CNP", sector: "Utilities" },
  { ticker: "D", sector: "Utilities" },
  { ticker: "DTE", sector: "Utilities" },
  { ticker: "DUK", sector: "Utilities" },
  { ticker: "ED", sector: "Utilities" },
  { ticker: "EIX", sector: "Utilities" },
  { ticker: "ES", sector: "Utilities" },
  { ticker: "ETR", sector: "Utilities" },
  { ticker: "EVRG", sector: "Utilities" },
  { ticker: "EXC", sector: "Utilities" },
  { ticker: "FE", sector: "Utilities" },
  { ticker: "LNT", sector: "Utilities" },
  { ticker: "NEE", sector: "Utilities" },
  { ticker: "NI", sector: "Utilities" },
  { ticker: "NRG", sector: "Utilities" },
  { ticker: "PCG", sector: "Utilities" },
  { ticker: "PEG", sector: "Utilities" },
  { ticker: "PNW", sector: "Utilities" },
  { ticker: "PPL", sector: "Utilities" },
  { ticker: "SO", sector: "Utilities" },
  { ticker: "SRE", sector: "Utilities" },
  { ticker: "VST", sector: "Utilities" },
  { ticker: "WEC", sector: "Utilities" },
  { ticker: "XEL", sector: "Utilities" },
];
